//------------------------------------------------------------------------------
// <auto-generated>
//     Flat Pricing Editor — Clean Designer (no BieuDoGio legacy)
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI
{
    partial class frmBangGia
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            this.panelTop = new System.Windows.Forms.Panel();
            this.slkSanPham = new DevExpress.XtraEditors.SearchLookUpEdit();
            this.searchLookUpEdit1View = new DevExpress.XtraGrid.Views.Grid.GridView();
            this.lblChonSP = new System.Windows.Forms.Label();
            this.lblTitle = new System.Windows.Forms.Label();
            this.panelLeft = new System.Windows.Forms.Panel();
            this.groupBoxThongTin = new Guna.UI2.WinForms.Guna2GroupBox();
            this.btnXoa = new Guna.UI2.WinForms.Guna2Button();
            this.btnSua = new Guna.UI2.WinForms.Guna2Button();
            this.btnThem = new Guna.UI2.WinForms.Guna2Button();
            this.txtGiaTien = new Guna.UI2.WinForms.Guna2TextBox();
            this.lblGiaTien = new System.Windows.Forms.Label();
            this.panelCenter = new System.Windows.Forms.Panel();
            this.groupBoxDanhSach = new Guna.UI2.WinForms.Guna2GroupBox();
            this.gridControlBangGia = new DevExpress.XtraGrid.GridControl();
            this.gridViewBangGia = new DevExpress.XtraGrid.Views.Grid.GridView();
            this.panelTop.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.slkSanPham.Properties)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.searchLookUpEdit1View)).BeginInit();
            this.panelLeft.SuspendLayout();
            this.groupBoxThongTin.SuspendLayout();
            this.panelCenter.SuspendLayout();
            this.groupBoxDanhSach.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.gridControlBangGia)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridViewBangGia)).BeginInit();
            this.SuspendLayout();
            // 
            // panelTop
            // 
            this.panelTop.Controls.Add(this.slkSanPham);
            this.panelTop.Controls.Add(this.lblChonSP);
            this.panelTop.Controls.Add(this.lblTitle);
            this.panelTop.Dock = System.Windows.Forms.DockStyle.Top;
            this.panelTop.Location = new System.Drawing.Point(0, 0);
            this.panelTop.Name = "panelTop";
            this.panelTop.Size = new System.Drawing.Size(1200, 74);
            this.panelTop.TabIndex = 0;
            // 
            // slkSanPham
            // 
            this.slkSanPham.Location = new System.Drawing.Point(520, 28);
            this.slkSanPham.Name = "slkSanPham";
            this.slkSanPham.Properties.Appearance.Options.UseFont = true;
            this.slkSanPham.Properties.Buttons.AddRange(new DevExpress.XtraEditors.Controls.EditorButton[] {
            new DevExpress.XtraEditors.Controls.EditorButton(DevExpress.XtraEditors.Controls.ButtonPredefines.Combo)});
            this.slkSanPham.Properties.NullText = "--- Gõ để tìm kiếm sản phẩm ---";
            this.slkSanPham.Properties.PopupView = this.searchLookUpEdit1View;
            this.slkSanPham.Size = new System.Drawing.Size(350, 20);
            this.slkSanPham.TabIndex = 2;
            // 
            // searchLookUpEdit1View
            // 
            this.searchLookUpEdit1View.FocusRectStyle = DevExpress.XtraGrid.Views.Grid.DrawFocusRectStyle.RowFocus;
            this.searchLookUpEdit1View.Name = "searchLookUpEdit1View";
            this.searchLookUpEdit1View.OptionsSelection.EnableAppearanceFocusedCell = false;
            this.searchLookUpEdit1View.OptionsView.ShowGroupPanel = false;
            // 
            // lblChonSP
            // 
            this.lblChonSP.AutoSize = true;
            this.lblChonSP.Location = new System.Drawing.Point(400, 32);
            this.lblChonSP.Name = "lblChonSP";
            this.lblChonSP.Size = new System.Drawing.Size(87, 13);
            this.lblChonSP.TabIndex = 1;
            this.lblChonSP.Text = "Chọn Sản Phẩm:";
            // 
            // lblTitle
            // 
            this.lblTitle.AutoSize = true;
            this.lblTitle.Location = new System.Drawing.Point(20, 25);
            this.lblTitle.Name = "lblTitle";
            this.lblTitle.Size = new System.Drawing.Size(155, 13);
            this.lblTitle.TabIndex = 0;
            this.lblTitle.Text = "QUẢN LÝ BẢNG GIÁ DỊCH VỤ";
            // 
            // panelLeft
            // 
            this.panelLeft.Controls.Add(this.groupBoxThongTin);
            this.panelLeft.Dock = System.Windows.Forms.DockStyle.Left;
            this.panelLeft.Location = new System.Drawing.Point(0, 74);
            this.panelLeft.Name = "panelLeft";
            this.panelLeft.Padding = new System.Windows.Forms.Padding(20, 10, 10, 20);
            this.panelLeft.Size = new System.Drawing.Size(380, 726);
            this.panelLeft.TabIndex = 1;
            // 
            // groupBoxThongTin
            // 
            this.groupBoxThongTin.Controls.Add(this.btnXoa);
            this.groupBoxThongTin.Controls.Add(this.btnSua);
            this.groupBoxThongTin.Controls.Add(this.btnThem);
            this.groupBoxThongTin.Controls.Add(this.txtGiaTien);
            this.groupBoxThongTin.Controls.Add(this.lblGiaTien);
            this.groupBoxThongTin.CustomBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(241)))), ((int)(((byte)(245)))), ((int)(((byte)(249)))));
            this.groupBoxThongTin.Dock = System.Windows.Forms.DockStyle.Top;
            this.groupBoxThongTin.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.groupBoxThongTin.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(125)))), ((int)(((byte)(137)))), ((int)(((byte)(149)))));
            this.groupBoxThongTin.Location = new System.Drawing.Point(20, 10);
            this.groupBoxThongTin.Name = "groupBoxThongTin";
            this.groupBoxThongTin.Size = new System.Drawing.Size(350, 280);
            this.groupBoxThongTin.TabIndex = 0;
            this.groupBoxThongTin.TabStop = false;
            this.groupBoxThongTin.Text = "Giá Ngày Thường (VNĐ)";
            // 
            // btnXoa
            // 
            this.btnXoa.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnXoa.ForeColor = System.Drawing.Color.White;
            this.btnXoa.Location = new System.Drawing.Point(20, 210);
            this.btnXoa.Name = "btnXoa";
            this.btnXoa.Size = new System.Drawing.Size(310, 38);
            this.btnXoa.TabIndex = 13;
            this.btnXoa.Text = " XÓA BẢNG GIÁ";
            this.btnXoa.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            // 
            // btnSua
            // 
            this.btnSua.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnSua.ForeColor = System.Drawing.Color.White;
            this.btnSua.Location = new System.Drawing.Point(20, 160);
            this.btnSua.Name = "btnSua";
            this.btnSua.Size = new System.Drawing.Size(310, 38);
            this.btnSua.TabIndex = 12;
            this.btnSua.Text = " CẬP NHẬT";
            this.btnSua.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            // 
            // btnThem
            // 
            this.btnThem.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnThem.ForeColor = System.Drawing.Color.White;
            this.btnThem.Location = new System.Drawing.Point(20, 110);
            this.btnThem.Name = "btnThem";
            this.btnThem.Size = new System.Drawing.Size(310, 38);
            this.btnThem.TabIndex = 11;
            this.btnThem.Text = " THÊM GIÁ MỚI";
            this.btnThem.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            // 
            // txtGiaTien
            // 
            this.txtGiaTien.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtGiaTien.DefaultText = "";
            this.txtGiaTien.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.txtGiaTien.Location = new System.Drawing.Point(20, 65);
            this.txtGiaTien.Name = "txtGiaTien";
            this.txtGiaTien.PlaceholderText = "";
            this.txtGiaTien.SelectedText = "";
            this.txtGiaTien.Size = new System.Drawing.Size(310, 30);
            this.txtGiaTien.TabIndex = 3;
            // 
            // lblGiaTien
            // 
            this.lblGiaTien.AutoSize = true;
            this.lblGiaTien.Location = new System.Drawing.Point(20, 45);
            this.lblGiaTien.Name = "lblGiaTien";
            this.lblGiaTien.Size = new System.Drawing.Size(87, 15);
            this.lblGiaTien.TabIndex = 2;
            this.lblGiaTien.Text = "Giá Tiền (VNĐ):";
            // 
            // panelCenter
            // 
            this.panelCenter.Controls.Add(this.groupBoxDanhSach);
            this.panelCenter.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelCenter.Location = new System.Drawing.Point(380, 74);
            this.panelCenter.Name = "panelCenter";
            this.panelCenter.Padding = new System.Windows.Forms.Padding(10, 10, 20, 20);
            this.panelCenter.Size = new System.Drawing.Size(820, 726);
            this.panelCenter.TabIndex = 2;
            // 
            // groupBoxDanhSach
            // 
            this.groupBoxDanhSach.Controls.Add(this.gridControlBangGia);
            this.groupBoxDanhSach.CustomBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(241)))), ((int)(((byte)(245)))), ((int)(((byte)(249)))));
            this.groupBoxDanhSach.Dock = System.Windows.Forms.DockStyle.Fill;
            this.groupBoxDanhSach.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.groupBoxDanhSach.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(125)))), ((int)(((byte)(137)))), ((int)(((byte)(149)))));
            this.groupBoxDanhSach.Location = new System.Drawing.Point(10, 10);
            this.groupBoxDanhSach.Name = "groupBoxDanhSach";
            this.groupBoxDanhSach.Padding = new System.Windows.Forms.Padding(10);
            this.groupBoxDanhSach.Size = new System.Drawing.Size(790, 696);
            this.groupBoxDanhSach.TabIndex = 0;
            this.groupBoxDanhSach.TabStop = false;
            this.groupBoxDanhSach.Text = "Flat Pricing Matrix";
            // 
            // gridControlBangGia
            // 
            this.gridControlBangGia.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gridControlBangGia.Location = new System.Drawing.Point(10, 50);
            this.gridControlBangGia.MainView = this.gridViewBangGia;
            this.gridControlBangGia.Name = "gridControlBangGia";
            this.gridControlBangGia.Size = new System.Drawing.Size(770, 636);
            this.gridControlBangGia.TabIndex = 0;
            this.gridControlBangGia.ViewCollection.AddRange(new DevExpress.XtraGrid.Views.Base.BaseView[] {
            this.gridViewBangGia});
            // 
            // gridViewBangGia
            // 
            this.gridViewBangGia.GridControl = this.gridControlBangGia;
            this.gridViewBangGia.Name = "gridViewBangGia";
            this.gridViewBangGia.OptionsBehavior.Editable = false;
            // 
            // frmBangGia
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1200, 800);
            this.Controls.Add(this.panelCenter);
            this.Controls.Add(this.panelLeft);
            this.Controls.Add(this.panelTop);
            this.Name = "frmBangGia";
            this.Text = "Quản lý bảng giá";
            this.panelTop.ResumeLayout(false);
            this.panelTop.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.slkSanPham.Properties)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.searchLookUpEdit1View)).EndInit();
            this.panelLeft.ResumeLayout(false);
            this.groupBoxThongTin.ResumeLayout(false);
            this.groupBoxThongTin.PerformLayout();
            this.panelCenter.ResumeLayout(false);
            this.groupBoxDanhSach.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.gridControlBangGia)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridViewBangGia)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel panelTop;
        private System.Windows.Forms.Label lblTitle;
        private DevExpress.XtraEditors.SearchLookUpEdit slkSanPham;
        private DevExpress.XtraGrid.Views.Grid.GridView searchLookUpEdit1View;
        private System.Windows.Forms.Label lblChonSP;
        private System.Windows.Forms.Panel panelLeft;
        private Guna.UI2.WinForms.Guna2GroupBox groupBoxThongTin;
        private System.Windows.Forms.Label lblGiaTien;
        private Guna.UI2.WinForms.Guna2TextBox txtGiaTien;
        private Guna.UI2.WinForms.Guna2Button btnThem;
        private Guna.UI2.WinForms.Guna2Button btnSua;
        private Guna.UI2.WinForms.Guna2Button btnXoa;
        private System.Windows.Forms.Panel panelCenter;
        private Guna.UI2.WinForms.Guna2GroupBox groupBoxDanhSach;
        private DevExpress.XtraGrid.GridControl gridControlBangGia;
        private DevExpress.XtraGrid.Views.Grid.GridView gridViewBangGia;
    }
}
