//------------------------------------------------------------------------------
// <auto-generated>
//     Máy phát sinh code thủ công cho DevExpress XtraUserControl
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.Modules.Kho
{
    partial class frmTrungTamKho
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }


        #region Windows Form Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.pnlAlert = new DevExpress.XtraEditors.PanelControl();
            this.lblAlertHSD = new DevExpress.XtraEditors.LabelControl();
            this.lblAlertTon = new DevExpress.XtraEditors.LabelControl();
            this.pnlMenu = new DevExpress.XtraEditors.PanelControl();
            this.lstPhieuGanDau = new DevExpress.XtraEditors.ImageListBoxControl();
            this.pnlPhieuActions = new DevExpress.XtraEditors.PanelControl();
            this.btnHuyPhieu = new DevExpress.XtraEditors.SimpleButton();
            this.btnDuyetPhieu = new DevExpress.XtraEditors.SimpleButton();
            this.lblListPhieu = new DevExpress.XtraEditors.LabelControl();
            this.btnCanhBao = new DevExpress.XtraEditors.SimpleButton();
            this.btnLichSu = new DevExpress.XtraEditors.SimpleButton();
            this.btnTonKho = new DevExpress.XtraEditors.SimpleButton();
            this.btnTaoPhieu = new DevExpress.XtraEditors.SimpleButton();
            this.pnlContent = new DevExpress.XtraEditors.PanelControl();
            ((System.ComponentModel.ISupportInitialize)(this.pnlAlert)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pnlMenu)).BeginInit();
            this.pnlMenu.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.lstPhieuGanDau)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pnlPhieuActions)).BeginInit();
            this.pnlPhieuActions.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pnlContent)).BeginInit();
            this.SuspendLayout();
            // 
            // pnlAlert
            // 
            this.pnlAlert.Appearance.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(243)))), ((int)(((byte)(224)))));
            this.pnlAlert.Appearance.Options.UseBackColor = true;
            this.pnlAlert.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder;
            this.pnlAlert.Dock = System.Windows.Forms.DockStyle.Top;
            this.pnlAlert.Location = new System.Drawing.Point(0, 0);
            this.pnlAlert.Name = "pnlAlert";
            this.pnlAlert.Size = new System.Drawing.Size(1200, 40);
            this.pnlAlert.TabIndex = 0;
            // 
            // lblAlertHSD
            // 
            this.lblAlertHSD.Appearance.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold);
            this.lblAlertHSD.Appearance.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(211)))), ((int)(((byte)(47)))), ((int)(((byte)(47)))));
            this.lblAlertHSD.Appearance.Options.UseFont = true;
            this.lblAlertHSD.Appearance.Options.UseForeColor = true;
            this.lblAlertHSD.Cursor = System.Windows.Forms.Cursors.Hand;
            this.lblAlertHSD.Location = new System.Drawing.Point(40, 11);
            this.lblAlertHSD.Name = "lblAlertHSD";
            this.lblAlertHSD.Size = new System.Drawing.Size(120, 17);
            this.lblAlertHSD.TabIndex = 2;
            this.lblAlertHSD.Text = "3 Lô sắp hết HSD";
            // 
            // lblAlertTon
            // 
            this.lblAlertTon.Appearance.Font = new System.Drawing.Font("Segoe UI", 9.75F, System.Drawing.FontStyle.Bold);
            this.lblAlertTon.Appearance.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(81)))), ((int)(((byte)(0)))));
            this.lblAlertTon.Appearance.Options.UseFont = true;
            this.lblAlertTon.Appearance.Options.UseForeColor = true;
            this.lblAlertTon.Cursor = System.Windows.Forms.Cursors.Hand;
            this.lblAlertTon.Location = new System.Drawing.Point(220, 11);
            this.lblAlertTon.Name = "lblAlertTon";
            this.lblAlertTon.Size = new System.Drawing.Size(200, 17);
            this.lblAlertTon.TabIndex = 3;
            this.lblAlertTon.Text = "2 Mặt hàng dưới mức tối thiểu";
            // 
            // pnlMenu
            // 
            this.pnlMenu.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder;
            this.pnlMenu.Controls.Add(this.lstPhieuGanDau);
            this.pnlMenu.Controls.Add(this.pnlPhieuActions);
            this.pnlMenu.Controls.Add(this.lblListPhieu);
            this.pnlMenu.Controls.Add(this.btnCanhBao);
            this.pnlMenu.Controls.Add(this.btnLichSu);
            this.pnlMenu.Controls.Add(this.btnTonKho);
            this.pnlMenu.Controls.Add(this.btnTaoPhieu);
            this.pnlMenu.Dock = System.Windows.Forms.DockStyle.Left;
            this.pnlMenu.Location = new System.Drawing.Point(0, 40);
            this.pnlMenu.Name = "pnlMenu";
            this.pnlMenu.Padding = new System.Windows.Forms.Padding(10);
            this.pnlMenu.Size = new System.Drawing.Size(272, 660);
            this.pnlMenu.TabIndex = 1;
            // 
            // lstPhieuGanDau
            // 
            this.lstPhieuGanDau.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lstPhieuGanDau.Location = new System.Drawing.Point(10, 205);
            this.lstPhieuGanDau.Name = "lstPhieuGanDau";
            this.lstPhieuGanDau.Size = new System.Drawing.Size(252, 395);
            this.lstPhieuGanDau.TabIndex = 5;
            this.lstPhieuGanDau.SelectedIndexChanged += new System.EventHandler(this.LstPhieuGanDau_SelectedIndexChanged);
            // 
            // pnlPhieuActions
            // 
            this.pnlPhieuActions.BorderStyle = DevExpress.XtraEditors.Controls.BorderStyles.NoBorder;
            this.pnlPhieuActions.Controls.Add(this.btnHuyPhieu);
            this.pnlPhieuActions.Controls.Add(this.btnDuyetPhieu);
            this.pnlPhieuActions.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.pnlPhieuActions.Location = new System.Drawing.Point(10, 600);
            this.pnlPhieuActions.Name = "pnlPhieuActions";
            this.pnlPhieuActions.Size = new System.Drawing.Size(252, 50);
            this.pnlPhieuActions.TabIndex = 6;
            // 
            // btnHuyPhieu
            // 
            this.btnHuyPhieu.Appearance.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(67)))), ((int)(((byte)(54)))));
            this.btnHuyPhieu.Appearance.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.btnHuyPhieu.Appearance.ForeColor = System.Drawing.Color.White;
            this.btnHuyPhieu.Appearance.Options.UseBackColor = true;
            this.btnHuyPhieu.Appearance.Options.UseFont = true;
            this.btnHuyPhieu.Appearance.Options.UseForeColor = true;
            this.btnHuyPhieu.Dock = System.Windows.Forms.DockStyle.Right;
            this.btnHuyPhieu.Enabled = false;
            this.btnHuyPhieu.ImageOptions.ImageUri.Uri = "Cancel";
            this.btnHuyPhieu.Location = new System.Drawing.Point(132, 0);
            this.btnHuyPhieu.Name = "btnHuyPhieu";
            this.btnHuyPhieu.Size = new System.Drawing.Size(120, 50);
            this.btnHuyPhieu.TabIndex = 1;
            this.btnHuyPhieu.Text = "Hủy";
            this.btnHuyPhieu.Click += new System.EventHandler(this.BtnHuyPhieu_Click);
            // 
            // btnDuyetPhieu
            // 
            this.btnDuyetPhieu.Appearance.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(76)))), ((int)(((byte)(175)))), ((int)(((byte)(80)))));
            this.btnDuyetPhieu.Appearance.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.btnDuyetPhieu.Appearance.ForeColor = System.Drawing.Color.White;
            this.btnDuyetPhieu.Appearance.Options.UseBackColor = true;
            this.btnDuyetPhieu.Appearance.Options.UseFont = true;
            this.btnDuyetPhieu.Appearance.Options.UseForeColor = true;
            this.btnDuyetPhieu.Dock = System.Windows.Forms.DockStyle.Left;
            this.btnDuyetPhieu.Enabled = false;
            this.btnDuyetPhieu.ImageOptions.ImageUri.Uri = "Apply";
            this.btnDuyetPhieu.Location = new System.Drawing.Point(0, 0);
            this.btnDuyetPhieu.Name = "btnDuyetPhieu";
            this.btnDuyetPhieu.Size = new System.Drawing.Size(120, 50);
            this.btnDuyetPhieu.TabIndex = 0;
            this.btnDuyetPhieu.Text = "Duyệt";
            this.btnDuyetPhieu.Click += new System.EventHandler(this.BtnDuyetPhieu_Click);
            // 
            // lblListPhieu
            // 
            this.lblListPhieu.Appearance.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblListPhieu.Appearance.ForeColor = System.Drawing.Color.Gray;
            this.lblListPhieu.Appearance.Options.UseFont = true;
            this.lblListPhieu.Appearance.Options.UseForeColor = true;
            this.lblListPhieu.Dock = System.Windows.Forms.DockStyle.Top;
            this.lblListPhieu.Location = new System.Drawing.Point(10, 170);
            this.lblListPhieu.Name = "lblListPhieu";
            this.lblListPhieu.Padding = new System.Windows.Forms.Padding(0, 15, 0, 5);
            this.lblListPhieu.Size = new System.Drawing.Size(109, 35);
            this.lblListPhieu.TabIndex = 4;
            this.lblListPhieu.Text = "DS PHIẾU GẦN ĐÂY";
            // 
            // btnCanhBao
            // 
            this.btnCanhBao.Appearance.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.btnCanhBao.Appearance.Options.UseFont = true;
            this.btnCanhBao.Appearance.Options.UseTextOptions = true;
            this.btnCanhBao.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Near;
            this.btnCanhBao.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnCanhBao.ImageOptions.ImageUri.Uri = "Warning";
            this.btnCanhBao.Location = new System.Drawing.Point(10, 130);
            this.btnCanhBao.Name = "btnCanhBao";
            this.btnCanhBao.Size = new System.Drawing.Size(252, 40);
            this.btnCanhBao.TabIndex = 3;
            this.btnCanhBao.Text = " CẢNH BÁO";
            this.btnCanhBao.Click += new System.EventHandler(this.btnCanhBao_Click);
            // 
            // btnLichSu
            // 
            this.btnLichSu.Appearance.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.btnLichSu.Appearance.Options.UseFont = true;
            this.btnLichSu.Appearance.Options.UseTextOptions = true;
            this.btnLichSu.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Near;
            this.btnLichSu.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnLichSu.ImageOptions.ImageUri.Uri = "List";
            this.btnLichSu.Location = new System.Drawing.Point(10, 90);
            this.btnLichSu.Name = "btnLichSu";
            this.btnLichSu.Size = new System.Drawing.Size(252, 40);
            this.btnLichSu.TabIndex = 2;
            this.btnLichSu.Text = " LỊCH SỬ GIAO DỊCH";
            this.btnLichSu.Click += new System.EventHandler(this.btnLichSu_Click);
            // 
            // btnTonKho
            // 
            this.btnTonKho.Appearance.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.btnTonKho.Appearance.Options.UseFont = true;
            this.btnTonKho.Appearance.Options.UseTextOptions = true;
            this.btnTonKho.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Near;
            this.btnTonKho.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnTonKho.ImageOptions.ImageUri.Uri = "Find";
            this.btnTonKho.Location = new System.Drawing.Point(10, 50);
            this.btnTonKho.Name = "btnTonKho";
            this.btnTonKho.Size = new System.Drawing.Size(252, 40);
            this.btnTonKho.TabIndex = 1;
            this.btnTonKho.Text = " TỒN KHO HIỆN TẠI";
            this.btnTonKho.Click += new System.EventHandler(this.btnTonKho_Click);
            // 
            // btnTaoPhieu
            // 
            this.btnTaoPhieu.Appearance.Font = new System.Drawing.Font("Segoe UI", 10F, System.Drawing.FontStyle.Bold);
            this.btnTaoPhieu.Appearance.Options.UseFont = true;
            this.btnTaoPhieu.Appearance.Options.UseTextOptions = true;
            this.btnTaoPhieu.Appearance.TextOptions.HAlignment = DevExpress.Utils.HorzAlignment.Near;
            this.btnTaoPhieu.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnTaoPhieu.ImageOptions.ImageUri.Uri = "Add";
            this.btnTaoPhieu.Location = new System.Drawing.Point(10, 10);
            this.btnTaoPhieu.Name = "btnTaoPhieu";
            this.btnTaoPhieu.Size = new System.Drawing.Size(252, 40);
            this.btnTaoPhieu.TabIndex = 0;
            this.btnTaoPhieu.Text = " TẠO / SỬA PHIẾU";
            this.btnTaoPhieu.Click += new System.EventHandler(this.btnTaoPhieu_Click);
            // 
            // pnlContent
            // 
            this.pnlContent.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlContent.Location = new System.Drawing.Point(272, 40);
            this.pnlContent.Name = "pnlContent";
            this.pnlContent.Size = new System.Drawing.Size(928, 660);
            this.pnlContent.TabIndex = 2;
            // 
            // frmTrungTamKho
            // 
            this.Controls.Add(this.pnlContent);
            this.Controls.Add(this.pnlMenu);
            this.Controls.Add(this.pnlAlert);
            this.Name = "frmTrungTamKho";
            this.Size = new System.Drawing.Size(1200, 700);
            this.Load += new System.EventHandler(this.frmTrungTamKho_Load);
            ((System.ComponentModel.ISupportInitialize)(this.pnlAlert)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pnlMenu)).EndInit();
            this.pnlMenu.ResumeLayout(false);
            this.pnlMenu.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.lstPhieuGanDau)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pnlPhieuActions)).EndInit();
            this.pnlPhieuActions.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pnlContent)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion
        private DevExpress.XtraEditors.PanelControl pnlAlert;
        private DevExpress.XtraEditors.LabelControl lblAlertHSD;
        private DevExpress.XtraEditors.LabelControl lblAlertTon;
        private DevExpress.XtraEditors.PanelControl pnlMenu;
        private DevExpress.XtraEditors.ImageListBoxControl lstPhieuGanDau;
        private DevExpress.XtraEditors.LabelControl lblListPhieu;
        private DevExpress.XtraEditors.SimpleButton btnCanhBao;
        private DevExpress.XtraEditors.SimpleButton btnLichSu;
        private DevExpress.XtraEditors.SimpleButton btnTonKho;
        private DevExpress.XtraEditors.SimpleButton btnTaoPhieu;
        private DevExpress.XtraEditors.PanelControl pnlContent;
        private DevExpress.XtraEditors.PanelControl pnlPhieuActions;
        private DevExpress.XtraEditors.SimpleButton btnDuyetPhieu;
        private DevExpress.XtraEditors.SimpleButton btnHuyPhieu;
        private System.ComponentModel.IContainer components = null;





    }}