using System;
using System.Collections.Generic;
using DAL;
using ET;

namespace BUS
{
    public interface IDonHangGateway
    {
        List<ET_DonHang> LoadDS();
        ET_DonHang LayTheoId(int id);
        ET_DonHang LayTheoMaCode(string maCode);
        bool Them(ET_DonHang et);
        int ThemVaLayId(ET_DonHang et);
        bool Sua(ET_DonHang et);
        bool Xoa(int id);
    }

    public interface IChiTietDonHangGateway { int ThemVaLayId(ET_ChiTietDonHang ct); bool Them(ET_ChiTietDonHang et); bool Xoa(int id); bool Sua(ET_ChiTietDonHang et); ET_ChiTietDonHang LayTheoId(int id); List<ET_ChiTietDonHang> LoadByDonHang(int idDonHang); List<ET_ChiTietDonHang> LoadDS(); }
    public interface IPhieuThuGateway { bool Them(ET_PhieuThu et); List<ET_PhieuThu> LoadDS(); }
    public interface IPhieuChiGateway { bool Them(ET_PhieuChi et); List<ET_PhieuChi> LoadDS(); }
    public interface ITheRfidGateway { ET_TheRFID LayTheoId(string maRfid); bool Sua(ET_TheRFID et); List<ET_TheRFID> LoadDS(); }
    public interface IViDienTuGateway { ET_ViDienTu LayTheoId(int id); ET_ViDienTu LayTheoKhachHang(int idKhachHang); bool Sua(ET_ViDienTu et); List<ET_ViDienTu> LoadDS(); bool Them(ET_ViDienTu et); bool Xoa(int id); }
    public interface IGiaoDichViGateway { bool Them(ET_GiaoDichVi et); int ThemVaLayId(ET_GiaoDichVi gd); List<ET_GiaoDichVi> LoadDS(); ET_GiaoDichVi LayTheoId(int id); }
    public interface IKhachHangGateway { ET_KhachHang LayTheoId(int id); void CapNhatChiTieuVaHang(int idKhachHang, decimal soTien); List<ET_KhachHang> LoadDS(); ET_KhachHang LayTheoMaCodeHoacSdt(string key); bool Them(ET_KhachHang et); bool Sua(ET_KhachHang et); bool Xoa(int id); List<ET_KhachHang> GetAll(); }
    public interface ISanPhamGateway { List<ET_SanPham> LoadDS(); ET_SanPham LayTheoId(int id); ET_SanPham LayTheoMaCode(string maCode); int ThemVaLayId(ET_SanPham et); bool Sua(ET_SanPham et); bool Xoa(int id); }
    public interface IComboGateway { List<ET_Combo> LoadDS(); ET_Combo LayTheoId(int id); bool Them(ET_Combo et); bool Sua(ET_Combo et); bool Xoa(int id); }
    public interface IComboChiTietGateway { List<ET_ComboChiTiet> LoadDS(); bool Them(ET_ComboChiTiet et); bool Xoa(int id); bool XoaTheoCombo(int idCombo); }
    public interface ISanPhamVeGateway { ET_SanPham_Ve LayTheoIdSanPham(int id); bool ThemHoacCapNhat(ET_SanPham_Ve et); bool Xoa(int idSanPham); }
    public interface IDatBanGateway { ET_DatBan LayTheoId(int id); List<ET_DatBan> LoadDS(); int ThemVaLayId(ET_DatBan et); bool Sua(ET_DatBan et); }
    public interface IBanAnGateway { List<ET_BanAn> LoadDS(); ET_BanAn LayTheoId(int id); bool Them(ET_BanAn et); bool Sua(ET_BanAn et); bool Xoa(int id); }
    public interface IChiTietDatBanGateway { bool Them(ET_ChiTietDatBan et); List<ET_ChiTietDatBan> LoadDS(); bool Xoa(int id); }
    public interface IDoanKhachDichVuGateway { int Them(ET_DoanKhach_DichVu et); List<ET_DoanKhach_DichVu> LayTheoDoan(int idDoan); bool Xoa(int id); bool Sua(ET_DoanKhach_DichVu et); List<ET_DoanKhach_DichVu> LayQuotaConLai(int idDoan); bool KhauTruQuota(int idDichVuDoan, int soLuong); ET_DoanKhach_DichVu LayTheoId(int id); }
    public interface ILuotVaoRaBaiXeGateway { int ThemVaLayId(ET_LuotVaoRaBaiXe et); bool Sua(ET_LuotVaoRaBaiXe et); ET_LuotVaoRaBaiXe LayTheoId(int id); List<ET_LuotVaoRaBaiXe> TimTheoBienSo(string bienSo); List<ET_LuotVaoRaBaiXe> LoadDangGui(); Dictionary<string, int> DemXeDangGuiTheoLoai(); int DemDaTraHomNay(); }
    public interface IVeDoXeChiTietGateway { bool Them(ET_VeDoXeChiTiet et); }
    public interface IGiaGuiXeGateway { ET_GiaGuiXe LayTheoLoaiXe(string loaiXe); List<ET_GiaGuiXe> LoadDS(); }
    public interface IVeDienTuGateway { bool Them(ET_VeDienTu et); bool Sua(ET_VeDienTu et); ET_VeDienTu LayTheoId(Guid id); List<ET_VeDienTu> LoadDS(); ET_VeDienTu LayTheoMaCode(string maCode); }
    public interface IKhoHangGateway { List<ET_KhoHang> LoadDS(); ET_KhoHang LayTheoId(int id); bool Them(ET_KhoHang et); bool Sua(ET_KhoHang et); }
    public interface ITonKhoGateway { List<ET_TonKho> LoadDS(); void DongBoTonKhoTrucTiepTuTheKho(); bool Sua(ET_TonKho et); bool Them(ET_TonKho et); }
    public interface ITheKhoGateway { List<ET_TheKho> LoadDS(); bool Them(ET_TheKho et); List<ET_TheKho> LayTheoSanPham(int idKho, int idSanPham); }
    public interface IDonViTinhGateway { List<ET_DonViTinh> LoadDS(); bool Them(ET_DonViTinh et); bool Sua(ET_DonViTinh et); bool Xoa(int id); }
    public interface IPhieuNhapKhoGateway { List<ET_PhieuNhapKho> LoadDS(); bool Them(ET_PhieuNhapKho et); bool Sua(ET_PhieuNhapKho et); bool Xoa(int id); ET_PhieuNhapKho LayTheoId(int id); int ThemHoanChinh(ET_PhieuNhapKho master, List<ET_ChiTietNhapKho> details); }
    public interface INhaCungCapGateway { List<ET_NhaCungCap> LoadDS(); ET_NhaCungCap LayTheoId(int id); bool Them(ET_NhaCungCap et); bool Sua(ET_NhaCungCap et); bool Xoa(int id); }
    public interface IPhieuXuatKhoGateway { List<ET_PhieuXuatKho> LoadDS(); bool Them(ET_PhieuXuatKho et); bool Sua(ET_PhieuXuatKho et); bool Xoa(int id); ET_PhieuXuatKho LayTheoId(int id); int ThemHoanChinh(ET_PhieuXuatKho master, List<ET_ChiTietXuatKho> details); }

    // --- Nhóm B Gateways ---
    public interface IChatLuongNuocGateway { List<ET_ChatLuongNuoc> LoadDS(); bool Them(ET_ChatLuongNuoc et); bool Sua(ET_ChatLuongNuoc et); bool Xoa(int id); }
    public interface IChoiNghiMatGateway { List<ET_ChoiNghiMat> LoadDS(); bool Them(ET_ChoiNghiMat et); bool Sua(ET_ChoiNghiMat et); bool Xoa(int id); }
    public interface IChuongTraiGateway { List<ET_ChuongTrai> LoadDS(); bool Them(ET_ChuongTrai et); bool Sua(ET_ChuongTrai et); bool Xoa(int id); }
    public interface IDongVatGateway { List<ET_DongVat> LoadDS(); bool Them(ET_DongVat et); bool Sua(ET_DongVat et); bool Xoa(int id); }
    public interface ILichChoAnGateway { List<ET_LichChoAn> LoadDS(); List<ET_LichChoAn> LoadTheoDongVat(int idDongVat); bool Them(ET_LichChoAn et); bool Sua(ET_LichChoAn et); bool Xoa(int id); }
    public interface ILichLamViecGateway { List<ET_LichLamViec> LoadTheoTuan(DateTime monday, string caLam); List<ET_LichLamViec> LoadTheoO(int idKhuVuc, DateTime ngay, string caLam); bool Them(int idNhanVien, int idKhuVuc, DateTime ngayLam, string caLam); bool Xoa(int id); int CopyTuan(DateTime mondayNguon, DateTime mondayDich, string caLam); List<int> LayDsIdNVDaPhanTrongNgay(DateTime ngay, string caLam); }
    public interface IKhuVucBienGateway { List<ET_KhuVucBien> LoadDS(); bool Them(ET_KhuVucBien et); bool Sua(ET_KhuVucBien et); bool Xoa(int id); List<ET_KhuVucBien> TimKiem(string keyword); }
    public interface IKhuVucThuGateway { List<ET_KhuVucThu> LoadDS(); bool Them(ET_KhuVucThu et); bool Sua(ET_KhuVucThu et); bool Xoa(int id); List<ET_KhuVucThu> TimKiem(string keyword); }
    public interface ITroChoiGateway { List<ET_TroChoi> LoadDS(); bool Them(ET_TroChoi et); bool Sua(ET_TroChoi et); bool Xoa(int id); List<ET_TroChoi> TimKiem(string keyword, string idKhuVuc); }
    public interface IDoanKhachGateway { List<ET_DoanKhach> LoadDS(); ET_DoanKhach LayTheoId(int id); bool Them(ET_DoanKhach et); bool Sua(ET_DoanKhach et); bool Xoa(int id); ET_DoanKhach LayTheoMaBookingHoacSdt(string key); bool DanhDauDaXuatVe(int idDoan); int ThemVaLayId(ET_DoanKhach et); }
    public interface IPhongGateway { List<ET_Phong> LoadDS(); ET_Phong LayTheoId(int id); bool Them(ET_Phong et); bool Sua(ET_Phong et); bool Xoa(int id); List<int> GetBusyRoomIds(DateTime start, DateTime end, int ignoreIdDatPhong); }
    public interface IKhuVucGateway { List<ET_KhuVuc> LoadDS(); ET_KhuVuc LayTheoId(int id); bool Them(ET_KhuVuc et); bool Sua(ET_KhuVuc et); bool Xoa(int id); }
    public interface IDatPhongChiTietGateway { ET_DatPhongChiTiet LayTheoId(int id); int ThemVaLayId(ET_DatPhongChiTiet et); bool Them(ET_DatPhongChiTiet et); bool Sua(ET_DatPhongChiTiet et); bool Xoa(int id); List<ET_DatPhongChiTiet> LoadDS(); }
    public interface IChiTietDatPhongGateway { bool Them(ET_ChiTietDatPhong et); bool Sua(ET_ChiTietDatPhong et); bool Xoa(int id); int ThemVaLayId(ET_ChiTietDatPhong et); List<ET_ChiTietDatPhong> LoadDS(); }
    public interface ISuCoGateway { List<ET_SuCo> LoadDS(); bool Them(ET_SuCo et); bool Sua(ET_SuCo et); bool Xoa(int id); List<ET_SuCo> LayTheoKhachHang(int idKhachHang); }
    public interface IThatLacGateway { List<ET_ThatLac> LoadDS(); bool Them(ET_ThatLac et); bool Sua(ET_ThatLac et); bool Xoa(int id); }
    public interface ILichBaoTriGateway { List<ET_LichBaoTri> LoadDS(); List<ET_LichBaoTri> LoadTheoThietBi(int idThietBi); bool Them(ET_LichBaoTri et); bool Sua(ET_LichBaoTri et); bool Xoa(int id); bool HoanTat(int id); List<ET_LichBaoTri> LayQuaHan(); }
    public interface IChiTietNhapKhoGateway { List<ET_ChiTietNhapKho> LoadDS(); bool Them(ET_ChiTietNhapKho et); bool Sua(ET_ChiTietNhapKho et); bool Xoa(int id); }
    public interface IChiTietXuatKhoGateway { List<ET_ChiTietXuatKho> LoadDS(); bool Them(ET_ChiTietXuatKho et); bool Sua(ET_ChiTietXuatKho et); bool Xoa(int id); }
    public interface IVaiTroGateway { List<ET_VaiTro> LoadDS(); ET_VaiTro LayTheoId(int id); bool Them(ET_VaiTro et); bool Sua(ET_VaiTro et); bool Xoa(int id); }
    public interface IPhanQuyenGateway { List<ET_PhanQuyen> LoadDS(); bool Them(ET_PhanQuyen et); bool XoaTheoVaiTro(int idVaiTro); }
    public interface INhaHangGateway { List<ET_NhaHang> LoadDS(); bool Them(ET_NhaHang et); bool Sua(ET_NhaHang et); bool Xoa(int id); }
    public interface IDanhSachThietBiGateway { List<ET_DanhSachThietBi> LoadDS(); List<ET_DanhSachThietBi> LoadDSTheoLoai(string loai); List<ET_DanhSachThietBi> TimKiem(string kw, string loai, string tt); bool Them(ET_DanhSachThietBi et); bool Sua(ET_DanhSachThietBi et); bool Xoa(int id); bool DoiTrangThai(int id, string tt); }
    public interface IQuyenHanGateway { List<ET_QuyenHan> LoadDS(); }
    public interface ILichSuDiemGateway { List<ET_LichSuDiem> LoadDS(); List<ET_LichSuDiem> LayTheoKhachHang(int idKhachHang); bool Them(ET_LichSuDiem et); }

    // --- Nhóm C Gateways ---
    public interface INhanVienGateway { List<ET_NhanVien> LoadDS(); ET_NhanVien LayTheoId(int id); bool Them(ET_NhanVien et); bool Sua(ET_NhanVien et); bool Xoa(int id); ET_NhanVien DangNhap(string username, string password); }
    public interface IKhuyenMaiGateway { List<ET_KhuyenMai> LoadDS(); bool Them(ET_KhuyenMai et); bool Sua(ET_KhuyenMai et); bool Xoa(int id); }
    public interface ISuKienGateway { List<ET_SuKien> LoadDS(); bool Them(ET_SuKien et); bool Sua(ET_SuKien et); bool Xoa(int id); }
    public interface IBangGiaGateway { List<ET_BangGia> LayTheoSanPham(int idSanPham); List<ET_BangGia> LayGiaHienTai(int idSanPham, TimeSpan gio); bool Them(ET_BangGia et); bool Sua(ET_BangGia et); bool Xoa(int id); }
    public interface ICauHinhNgayLeGateway { bool LaNgayLe(DateTime ngay); }
    public interface IQuyDoiDonViGateway { List<ET_QuyDoiDonVi> LoadDS(); bool Them(ET_QuyDoiDonVi et); bool Sua(ET_QuyDoiDonVi et); bool Xoa(int id); }
    public interface IQuyTacDiemGateway { List<ET_QuyTacDiem> LoadDS(); List<ET_QuyTacDiem> LayQuyTacActive(); }
    public interface IThueDoChiTietGateway { List<ET_ThueDoChiTiet> LoadDS(); bool Them(ET_ThueDoChiTiet et); bool Sua(ET_ThueDoChiTiet et); ET_ThueDoChiTiet LayTheoId(int id); }

    internal class DefaultDonHangGateway : IDonHangGateway
    {
        public List<ET_DonHang> LoadDS() => DAL_DonHang.Instance.LoadDS();
        public ET_DonHang LayTheoId(int id) => DAL_DonHang.Instance.LayTheoId(id);
        public ET_DonHang LayTheoMaCode(string maCode) => DAL_DonHang.Instance.LayTheoMaCode(maCode);
        public bool Them(ET_DonHang et) => DAL_DonHang.Instance.Them(et);
        public int ThemVaLayId(ET_DonHang et) => DAL_DonHang.Instance.ThemVaLayId(et);
        public bool Sua(ET_DonHang et) => DAL_DonHang.Instance.Sua(et);
        public bool Xoa(int id) => DAL_DonHang.Instance.Xoa(id);
    }

    internal class DefaultChiTietDonHangGateway : IChiTietDonHangGateway { public int ThemVaLayId(ET_ChiTietDonHang ct) => DAL_ChiTietDonHang.Instance.ThemVaLayId(ct); public bool Them(ET_ChiTietDonHang et) => DAL_ChiTietDonHang.Instance.Them(et); public bool Xoa(int id) => DAL_ChiTietDonHang.Instance.Xoa(id); public bool Sua(ET_ChiTietDonHang et) => DAL_ChiTietDonHang.Instance.Sua(et); public ET_ChiTietDonHang LayTheoId(int id) => DAL_ChiTietDonHang.Instance.LayTheoId(id); public List<ET_ChiTietDonHang> LoadByDonHang(int idDonHang) => DAL_ChiTietDonHang.Instance.LoadByDonHang(idDonHang); public List<ET_ChiTietDonHang> LoadDS() => DAL_ChiTietDonHang.Instance.LoadDS(); }
    internal class DefaultPhieuThuGateway : IPhieuThuGateway { public bool Them(ET_PhieuThu et) => DAL_PhieuThu.Instance.Them(et); public List<ET_PhieuThu> LoadDS() => DAL_PhieuThu.Instance.LoadDS(); }
    internal class DefaultPhieuChiGateway : IPhieuChiGateway { public bool Them(ET_PhieuChi et) => DAL_PhieuChi.Instance.Them(et); public List<ET_PhieuChi> LoadDS() => DAL_PhieuChi.Instance.LoadDS(); }
    internal class DefaultTheRfidGateway : ITheRfidGateway { public ET_TheRFID LayTheoId(string maRfid) => DAL_TheRFID.Instance.LayTheoId(maRfid); public bool Sua(ET_TheRFID et) => DAL_TheRFID.Instance.Sua(et); public List<ET_TheRFID> LoadDS() => DAL_TheRFID.Instance.LoadDS(); }
    internal class DefaultViDienTuGateway : IViDienTuGateway
    {
        public ET_ViDienTu LayTheoId(int id) => DAL_ViDienTu.Instance.LayTheoId(id);
        public ET_ViDienTu LayTheoKhachHang(int idKhachHang) => DAL_ViDienTu.Instance.LayTheoKhachHang(idKhachHang);
        public bool Sua(ET_ViDienTu et) => DAL_ViDienTu.Instance.Sua(et);
        public List<ET_ViDienTu> LoadDS() => DAL_ViDienTu.Instance.LoadDS();
        public bool Them(ET_ViDienTu et) => DAL_ViDienTu.Instance.Them(et);
        public bool Xoa(int id) => DAL_ViDienTu.Instance.Xoa(id);
    }
    internal class DefaultGiaoDichViGateway : IGiaoDichViGateway { public bool Them(ET_GiaoDichVi et) => DAL_GiaoDichVi.Instance.Them(et); public int ThemVaLayId(ET_GiaoDichVi gd) => DAL_GiaoDichVi.Instance.ThemVaLayId(gd); public List<ET_GiaoDichVi> LoadDS() => DAL_GiaoDichVi.Instance.LoadDS(); public ET_GiaoDichVi LayTheoId(int id) => DAL_GiaoDichVi.Instance.LayTheoId(id); }
    internal class DefaultKhachHangGateway : IKhachHangGateway { public ET_KhachHang LayTheoId(int id) => DAL_KhachHang.Instance.LayTheoId(id); public void CapNhatChiTieuVaHang(int idKhachHang, decimal soTien) => DAL_KhachHang.Instance.CapNhatChiTieuVaHang(idKhachHang, soTien); public List<ET_KhachHang> LoadDS() => DAL_KhachHang.Instance.LoadDS(); public ET_KhachHang LayTheoMaCodeHoacSdt(string key) => DAL_KhachHang.Instance.LayTheoMaCodeHoacSdt(key); public bool Them(ET_KhachHang et) => DAL_KhachHang.Instance.Them(et); public bool Sua(ET_KhachHang et) => DAL_KhachHang.Instance.Sua(et); public bool Xoa(int id) => DAL_KhachHang.Instance.Xoa(id); public List<ET_KhachHang> GetAll() => DAL_KhachHang.Instance.GetAll(); }
    internal class DefaultSanPhamGateway : ISanPhamGateway { public List<ET_SanPham> LoadDS() => DAL_SanPham.Instance.LoadDS(); public ET_SanPham LayTheoId(int id) => DAL_SanPham.Instance.LayTheoId(id); public ET_SanPham LayTheoMaCode(string maCode) => DAL_SanPham.Instance.LayTheoMaCode(maCode); public int ThemVaLayId(ET_SanPham et) => DAL_SanPham.Instance.ThemVaLayId(et); public bool Sua(ET_SanPham et) => DAL_SanPham.Instance.Sua(et); public bool Xoa(int id) => DAL_SanPham.Instance.Xoa(id); }
    internal class DefaultComboGateway : IComboGateway { public List<ET_Combo> LoadDS() => DAL_Combo.Instance.LoadDS(); public ET_Combo LayTheoId(int id) => DAL_Combo.Instance.LayTheoId(id); public bool Them(ET_Combo et) => DAL_Combo.Instance.Them(et); public bool Sua(ET_Combo et) => DAL_Combo.Instance.Sua(et); public bool Xoa(int id) => DAL_Combo.Instance.Xoa(id); }
    internal class DefaultComboChiTietGateway : IComboChiTietGateway { public List<ET_ComboChiTiet> LoadDS() => DAL_ComboChiTiet.Instance.LoadDS(); public bool Them(ET_ComboChiTiet et) => DAL_ComboChiTiet.Instance.Them(et); public bool Xoa(int id) => DAL_ComboChiTiet.Instance.Xoa(id); public bool XoaTheoCombo(int idCombo) => DAL_ComboChiTiet.Instance.XoaTheoCombo(idCombo); }
    internal class DefaultSanPhamVeGateway : ISanPhamVeGateway { public ET_SanPham_Ve LayTheoIdSanPham(int id) => DAL_SanPham_Ve.Instance.LayTheoIdSanPham(id); public bool ThemHoacCapNhat(ET_SanPham_Ve et) => DAL_SanPham_Ve.Instance.ThemHoacCapNhat(et); public bool Xoa(int idSanPham) => DAL_SanPham_Ve.Instance.Xoa(idSanPham); }
    internal class DefaultDatBanGateway : IDatBanGateway { public ET_DatBan LayTheoId(int id) => DAL_DatBan.Instance.LayTheoId(id); public List<ET_DatBan> LoadDS() => DAL_DatBan.Instance.LoadDS(); public int ThemVaLayId(ET_DatBan et) => DAL_DatBan.Instance.ThemVaLayId(et); public bool Sua(ET_DatBan et) => DAL_DatBan.Instance.Sua(et); }
    internal class DefaultBanAnGateway : IBanAnGateway { public List<ET_BanAn> LoadDS() => DAL_BanAn.Instance.LoadDS(); public ET_BanAn LayTheoId(int id) => DAL_BanAn.Instance.LayTheoId(id); public bool Them(ET_BanAn et) => DAL_BanAn.Instance.Them(et); public bool Sua(ET_BanAn et) => DAL_BanAn.Instance.Sua(et); public bool Xoa(int id) => DAL_BanAn.Instance.Xoa(id); }
    internal class DefaultChiTietDatBanGateway : IChiTietDatBanGateway { public bool Them(ET_ChiTietDatBan et) => DAL_ChiTietDatBan.Instance.Them(et); public List<ET_ChiTietDatBan> LoadDS() => DAL_ChiTietDatBan.Instance.LoadDS(); public bool Xoa(int id) => DAL_ChiTietDatBan.Instance.Xoa(id); }
    internal class DefaultDoanKhachDichVuGateway : IDoanKhachDichVuGateway { public int Them(ET_DoanKhach_DichVu et) => DAL_DoanKhach_DichVu.Instance.Them(et); public List<ET_DoanKhach_DichVu> LayTheoDoan(int idDoan) => DAL_DoanKhach_DichVu.Instance.LayTheoDoan(idDoan); public bool Xoa(int id) => DAL_DoanKhach_DichVu.Instance.Xoa(id); public bool Sua(ET_DoanKhach_DichVu et) => DAL_DoanKhach_DichVu.Instance.Sua(et); public List<ET_DoanKhach_DichVu> LayQuotaConLai(int idDoan) => DAL_DoanKhach_DichVu.Instance.LayQuotaConLai(idDoan); public bool KhauTruQuota(int idDichVuDoan, int soLuong) => DAL_DoanKhach_DichVu.Instance.KhauTruQuota(idDichVuDoan, soLuong); public ET_DoanKhach_DichVu LayTheoId(int id) => DAL_DoanKhach_DichVu.Instance.LayTheoId(id); }
    internal class DefaultLuotVaoRaBaiXeGateway : ILuotVaoRaBaiXeGateway { public int ThemVaLayId(ET_LuotVaoRaBaiXe et) => DAL_LuotVaoRaBaiXe.Instance.ThemVaLayId(et); public bool Sua(ET_LuotVaoRaBaiXe et) => DAL_LuotVaoRaBaiXe.Instance.Sua(et); public ET_LuotVaoRaBaiXe LayTheoId(int id) => DAL_LuotVaoRaBaiXe.Instance.LayTheoId(id); public List<ET_LuotVaoRaBaiXe> TimTheoBienSo(string bienSo) => DAL_LuotVaoRaBaiXe.Instance.TimTheoBienSo(bienSo); public List<ET_LuotVaoRaBaiXe> LoadDangGui() => DAL_LuotVaoRaBaiXe.Instance.LoadDangGui(); public Dictionary<string, int> DemXeDangGuiTheoLoai() => DAL_LuotVaoRaBaiXe.Instance.DemXeDangGuiTheoLoai(); public int DemDaTraHomNay() => DAL_LuotVaoRaBaiXe.Instance.DemDaTraHomNay(); }
    internal class DefaultVeDoXeChiTietGateway : IVeDoXeChiTietGateway { public bool Them(ET_VeDoXeChiTiet et) => DAL_VeDoXeChiTiet.Instance.Them(et); }
    internal class DefaultGiaGuiXeGateway : IGiaGuiXeGateway { public ET_GiaGuiXe LayTheoLoaiXe(string loaiXe) => DAL_GiaGuiXe.Instance.LayTheoLoaiXe(loaiXe); public List<ET_GiaGuiXe> LoadDS() => DAL_GiaGuiXe.Instance.LoadDS(); }
    internal class DefaultVeDienTuGateway : IVeDienTuGateway { public bool Them(ET_VeDienTu et) => DAL_VeDienTu.Instance.Them(et); public bool Sua(ET_VeDienTu et) => DAL_VeDienTu.Instance.Sua(et); public ET_VeDienTu LayTheoId(Guid id) => DAL_VeDienTu.Instance.LayTheoId(id); public List<ET_VeDienTu> LoadDS() => DAL_VeDienTu.Instance.LoadDS(); public ET_VeDienTu LayTheoMaCode(string maCode) => DAL_VeDienTu.Instance.LayTheoMaCode(maCode); }
    internal class DefaultKhoHangGateway : IKhoHangGateway { public List<ET_KhoHang> LoadDS() => DAL_KhoHang.Instance.LoadDS(); public ET_KhoHang LayTheoId(int id) => DAL_KhoHang.Instance.LayTheoId(id); public bool Them(ET_KhoHang et) => DAL_KhoHang.Instance.Them(et); public bool Sua(ET_KhoHang et) => DAL_KhoHang.Instance.Sua(et); }
    internal class DefaultTonKhoGateway : ITonKhoGateway { public List<ET_TonKho> LoadDS() => DAL_TonKho.Instance.LoadDS(); public void DongBoTonKhoTrucTiepTuTheKho() => DAL_TonKho.Instance.DongBoTonKhoTrucTiepTuTheKho(); public bool Sua(ET_TonKho et) => DAL_TonKho.Instance.Sua(et); public bool Them(ET_TonKho et) => DAL_TonKho.Instance.Them(et); }
    internal class DefaultTheKhoGateway : ITheKhoGateway { public List<ET_TheKho> LoadDS() => DAL_TheKho.Instance.LoadDS(); public bool Them(ET_TheKho et) => DAL_TheKho.Instance.Them(et); public List<ET_TheKho> LayTheoSanPham(int idKho, int idSanPham) => DAL_TheKho.Instance.LayTheoSanPham(idKho, idSanPham); }
    internal class DefaultDonViTinhGateway : IDonViTinhGateway { public List<ET_DonViTinh> LoadDS() => DAL_DonViTinh.Instance.LoadDS(); public bool Them(ET_DonViTinh et) => DAL_DonViTinh.Instance.Them(et); public bool Sua(ET_DonViTinh et) => DAL_DonViTinh.Instance.Sua(et); public bool Xoa(int id) => DAL_DonViTinh.Instance.Xoa(id); }
    internal class DefaultPhieuNhapKhoGateway : IPhieuNhapKhoGateway { public List<ET_PhieuNhapKho> LoadDS() => DAL_PhieuNhapKho.Instance.LoadDS(); public bool Them(ET_PhieuNhapKho et) => DAL_PhieuNhapKho.Instance.Them(et); public bool Sua(ET_PhieuNhapKho et) => DAL_PhieuNhapKho.Instance.Sua(et); public bool Xoa(int id) => DAL_PhieuNhapKho.Instance.Xoa(id); public ET_PhieuNhapKho LayTheoId(int id) => DAL_PhieuNhapKho.Instance.LayTheoId(id); public int ThemHoanChinh(ET_PhieuNhapKho master, List<ET_ChiTietNhapKho> details) => DAL_PhieuNhapKho.Instance.ThemHoanChinh(master, details); }
    internal class DefaultNhaCungCapGateway : INhaCungCapGateway { public List<ET_NhaCungCap> LoadDS() => DAL_NhaCungCap.Instance.LoadDS(); public ET_NhaCungCap LayTheoId(int id) => DAL_NhaCungCap.Instance.LayTheoId(id); public bool Them(ET_NhaCungCap et) => DAL_NhaCungCap.Instance.Them(et); public bool Sua(ET_NhaCungCap et) => DAL_NhaCungCap.Instance.Sua(et); public bool Xoa(int id) => DAL_NhaCungCap.Instance.Xoa(id); }

    // --- Nhóm B Default Gateways ---
    internal class DefaultChatLuongNuocGateway : IChatLuongNuocGateway { public List<ET_ChatLuongNuoc> LoadDS() => DAL_ChatLuongNuoc.Instance.LoadDS(); public bool Them(ET_ChatLuongNuoc et) => DAL_ChatLuongNuoc.Instance.Them(et); public bool Sua(ET_ChatLuongNuoc et) => DAL_ChatLuongNuoc.Instance.Sua(et); public bool Xoa(int id) => DAL_ChatLuongNuoc.Instance.Xoa(id); }
    internal class DefaultChoiNghiMatGateway : IChoiNghiMatGateway { public List<ET_ChoiNghiMat> LoadDS() => DAL_ChoiNghiMat.Instance.LoadDS(); public bool Them(ET_ChoiNghiMat et) => DAL_ChoiNghiMat.Instance.Them(et); public bool Sua(ET_ChoiNghiMat et) => DAL_ChoiNghiMat.Instance.Sua(et); public bool Xoa(int id) => DAL_ChoiNghiMat.Instance.Xoa(id); }
    internal class DefaultChuongTraiGateway : IChuongTraiGateway { public List<ET_ChuongTrai> LoadDS() => DAL_ChuongTrai.Instance.LoadDS(); public bool Them(ET_ChuongTrai et) => DAL_ChuongTrai.Instance.Them(et); public bool Sua(ET_ChuongTrai et) => DAL_ChuongTrai.Instance.Sua(et); public bool Xoa(int id) => DAL_ChuongTrai.Instance.Xoa(id); }
    internal class DefaultDongVatGateway : IDongVatGateway { public List<ET_DongVat> LoadDS() => DAL_DongVat.Instance.LoadDS(); public bool Them(ET_DongVat et) => DAL_DongVat.Instance.Them(et); public bool Sua(ET_DongVat et) => DAL_DongVat.Instance.Sua(et); public bool Xoa(int id) => DAL_DongVat.Instance.Xoa(id); }
    internal class DefaultLichChoAnGateway : ILichChoAnGateway { public List<ET_LichChoAn> LoadDS() => DAL_LichChoAn.Instance.LoadDS(); public List<ET_LichChoAn> LoadTheoDongVat(int idDongVat) => DAL_LichChoAn.Instance.LoadTheoDongVat(idDongVat); public bool Them(ET_LichChoAn et) => DAL_LichChoAn.Instance.Them(et); public bool Sua(ET_LichChoAn et) => DAL_LichChoAn.Instance.Sua(et); public bool Xoa(int id) => DAL_LichChoAn.Instance.Xoa(id); }
    internal class DefaultLichLamViecGateway : ILichLamViecGateway { public List<ET_LichLamViec> LoadTheoTuan(DateTime monday, string caLam) => DAL_LichLamViec.Instance.LoadTheoTuan(monday, caLam); public List<ET_LichLamViec> LoadTheoO(int idKhuVuc, DateTime ngay, string caLam) => DAL_LichLamViec.Instance.LoadTheoO(idKhuVuc, ngay, caLam); public bool Them(int idNhanVien, int idKhuVuc, DateTime ngayLam, string caLam) => DAL_LichLamViec.Instance.Them(idNhanVien, idKhuVuc, ngayLam, caLam); public bool Xoa(int id) => DAL_LichLamViec.Instance.Xoa(id); public int CopyTuan(DateTime mondayNguon, DateTime mondayDich, string caLam) => DAL_LichLamViec.Instance.CopyTuan(mondayNguon, mondayDich, caLam); public List<int> LayDsIdNVDaPhanTrongNgay(DateTime ngay, string caLam) => DAL_LichLamViec.Instance.LayDsIdNVDaPhanTrongNgay(ngay, caLam); }
    internal class DefaultKhuVucBienGateway : IKhuVucBienGateway { public List<ET_KhuVucBien> LoadDS() => DAL_KhuVucBien.Instance.LoadDS(); public bool Them(ET_KhuVucBien et) => DAL_KhuVucBien.Instance.Them(et); public bool Sua(ET_KhuVucBien et) => DAL_KhuVucBien.Instance.Sua(et); public bool Xoa(int id) => DAL_KhuVucBien.Instance.Xoa(id); public List<ET_KhuVucBien> TimKiem(string keyword) => DAL_KhuVucBien.Instance.TimKiem(keyword); }
    internal class DefaultKhuVucThuGateway : IKhuVucThuGateway { public List<ET_KhuVucThu> LoadDS() => DAL_KhuVucThu.Instance.LoadDS(); public bool Them(ET_KhuVucThu et) => DAL_KhuVucThu.Instance.Them(et); public bool Sua(ET_KhuVucThu et) => DAL_KhuVucThu.Instance.Sua(et); public bool Xoa(int id) => DAL_KhuVucThu.Instance.Xoa(id); public List<ET_KhuVucThu> TimKiem(string keyword) => DAL_KhuVucThu.Instance.TimKiem(keyword); }
    internal class DefaultTroChoiGateway : ITroChoiGateway { public List<ET_TroChoi> LoadDS() => DAL_TroChoi.Instance.LoadDS(); public bool Them(ET_TroChoi et) => DAL_TroChoi.Instance.Them(et); public bool Sua(ET_TroChoi et) => DAL_TroChoi.Instance.Sua(et); public bool Xoa(int id) => DAL_TroChoi.Instance.Xoa(id); public List<ET_TroChoi> TimKiem(string keyword, string idKhuVuc) => DAL_TroChoi.Instance.TimKiem(keyword, idKhuVuc); }
    internal class DefaultPhieuXuatKhoGateway : IPhieuXuatKhoGateway { public List<ET_PhieuXuatKho> LoadDS() => DAL_PhieuXuatKho.Instance.LoadDS(); public bool Them(ET_PhieuXuatKho et) => DAL_PhieuXuatKho.Instance.Them(et); public bool Sua(ET_PhieuXuatKho et) => DAL_PhieuXuatKho.Instance.Sua(et); public bool Xoa(int id) => DAL_PhieuXuatKho.Instance.Xoa(id); public ET_PhieuXuatKho LayTheoId(int id) => DAL_PhieuXuatKho.Instance.LayTheoId(id); public int ThemHoanChinh(ET_PhieuXuatKho master, List<ET_ChiTietXuatKho> details) => DAL_PhieuXuatKho.Instance.ThemHoanChinh(master, details); }
    internal class DefaultDoanKhachGateway : IDoanKhachGateway { public int ThemVaLayId(ET_DoanKhach et) => DAL_DoanKhach.Instance.ThemVaLayId(et); public List<ET_DoanKhach> LoadDS() => DAL_DoanKhach.Instance.LoadDS(); public ET_DoanKhach LayTheoId(int id) => DAL_DoanKhach.Instance.LayTheoId(id); public bool Them(ET_DoanKhach et) => DAL_DoanKhach.Instance.Them(et); public bool Sua(ET_DoanKhach et) => DAL_DoanKhach.Instance.Sua(et); public bool Xoa(int id) => DAL_DoanKhach.Instance.Xoa(id); public ET_DoanKhach LayTheoMaBookingHoacSdt(string key) => DAL_DoanKhach.Instance.LayTheoMaBookingHoacSdt(key); public bool DanhDauDaXuatVe(int idDoan) => DAL_DoanKhach.Instance.DanhDauDaXuatVe(idDoan); }
    internal class DefaultPhongGateway : IPhongGateway { public List<ET_Phong> LoadDS() => DAL_Phong.Instance.LoadDS(); public ET_Phong LayTheoId(int id) => DAL_Phong.Instance.LayTheoId(id); public bool Them(ET_Phong et) => DAL_Phong.Instance.Them(et); public bool Sua(ET_Phong et) => DAL_Phong.Instance.Sua(et); public bool Xoa(int id) => DAL_Phong.Instance.Xoa(id); public List<int> GetBusyRoomIds(DateTime start, DateTime end, int ignoreIdDatPhong) => DAL_Phong.Instance.GetBusyRoomIds(start, end, ignoreIdDatPhong); }
    internal class DefaultKhuVucGateway : IKhuVucGateway { public List<ET_KhuVuc> LoadDS() => DAL_KhuVuc.Instance.LoadDS(); public ET_KhuVuc LayTheoId(int id) => DAL_KhuVuc.Instance.LayTheoId(id); public bool Them(ET_KhuVuc et) => DAL_KhuVuc.Instance.Them(et); public bool Sua(ET_KhuVuc et) => DAL_KhuVuc.Instance.Sua(et); public bool Xoa(int id) => DAL_KhuVuc.Instance.Xoa(id); }
    internal class DefaultDatPhongChiTietGateway : IDatPhongChiTietGateway { public ET_DatPhongChiTiet LayTheoId(int id) => DAL_DatPhongChiTiet.Instance.LayTheoId(id); public int ThemVaLayId(ET_DatPhongChiTiet et) => DAL_DatPhongChiTiet.Instance.ThemVaLayId(et); public bool Them(ET_DatPhongChiTiet et) => DAL_DatPhongChiTiet.Instance.Them(et); public bool Sua(ET_DatPhongChiTiet et) => DAL_DatPhongChiTiet.Instance.Sua(et); public bool Xoa(int id) => DAL_DatPhongChiTiet.Instance.Xoa(id); public List<ET_DatPhongChiTiet> LoadDS() => DAL_DatPhongChiTiet.Instance.LoadDS(); }
    internal class DefaultChiTietDatPhongGateway : IChiTietDatPhongGateway { public bool Them(ET_ChiTietDatPhong et) => DAL_ChiTietDatPhong.Instance.Them(et); public bool Sua(ET_ChiTietDatPhong et) => DAL_ChiTietDatPhong.Instance.Sua(et); public bool Xoa(int id) => DAL_ChiTietDatPhong.Instance.Xoa(id); public int ThemVaLayId(ET_ChiTietDatPhong et) => DAL_ChiTietDatPhong.Instance.ThemVaLayId(et); public List<ET_ChiTietDatPhong> LoadDS() => DAL_ChiTietDatPhong.Instance.LoadDS(); }
    internal class DefaultSuCoGateway : ISuCoGateway { public List<ET_SuCo> LoadDS() => DAL_SuCo.Instance.LoadDS(); public bool Them(ET_SuCo et) => DAL_SuCo.Instance.Them(et); public bool Sua(ET_SuCo et) => DAL_SuCo.Instance.Sua(et); public bool Xoa(int id) => DAL_SuCo.Instance.Xoa(id); public List<ET_SuCo> LayTheoKhachHang(int idKhachHang) => DAL_SuCo.Instance.LayTheoKhachHang(idKhachHang); }
    internal class DefaultThatLacGateway : IThatLacGateway { public List<ET_ThatLac> LoadDS() => DAL_ThatLac.Instance.LoadDS(); public bool Them(ET_ThatLac et) => DAL_ThatLac.Instance.Them(et); public bool Sua(ET_ThatLac et) => DAL_ThatLac.Instance.Sua(et); public bool Xoa(int id) => DAL_ThatLac.Instance.Xoa(id); }
    internal class DefaultLichBaoTriGateway : ILichBaoTriGateway { public List<ET_LichBaoTri> LoadDS() => DAL_LichBaoTri.Instance.LoadDS(); public List<ET_LichBaoTri> LoadTheoThietBi(int idThietBi) => DAL_LichBaoTri.Instance.LoadTheoThietBi(idThietBi); public bool Them(ET_LichBaoTri et) => DAL_LichBaoTri.Instance.Them(et); public bool Sua(ET_LichBaoTri et) => DAL_LichBaoTri.Instance.Sua(et); public bool Xoa(int id) => DAL_LichBaoTri.Instance.Xoa(id); public bool HoanTat(int id) => DAL_LichBaoTri.Instance.HoanTat(id); public List<ET_LichBaoTri> LayQuaHan() => DAL_LichBaoTri.Instance.LayQuaHan(); }
    internal class DefaultChiTietNhapKhoGateway : IChiTietNhapKhoGateway { public List<ET_ChiTietNhapKho> LoadDS() => DAL_ChiTietNhapKho.Instance.LoadDS(); public bool Them(ET_ChiTietNhapKho et) => DAL_ChiTietNhapKho.Instance.Them(et); public bool Sua(ET_ChiTietNhapKho et) => DAL_ChiTietNhapKho.Instance.Sua(et); public bool Xoa(int id) => DAL_ChiTietNhapKho.Instance.Xoa(id); }
    internal class DefaultChiTietXuatKhoGateway : IChiTietXuatKhoGateway { public List<ET_ChiTietXuatKho> LoadDS() => DAL_ChiTietXuatKho.Instance.LoadDS(); public bool Them(ET_ChiTietXuatKho et) => DAL_ChiTietXuatKho.Instance.Them(et); public bool Sua(ET_ChiTietXuatKho et) => DAL_ChiTietXuatKho.Instance.Sua(et); public bool Xoa(int id) => DAL_ChiTietXuatKho.Instance.Xoa(id); }
    internal class DefaultVaiTroGateway : IVaiTroGateway { public List<ET_VaiTro> LoadDS() => DAL_VaiTro.Instance.LoadDS(); public ET_VaiTro LayTheoId(int id) => DAL_VaiTro.Instance.LayTheoId(id); public bool Them(ET_VaiTro et) => DAL_VaiTro.Instance.Them(et); public bool Sua(ET_VaiTro et) => DAL_VaiTro.Instance.Sua(et); public bool Xoa(int id) => DAL_VaiTro.Instance.Xoa(id); }
    internal class DefaultPhanQuyenGateway : IPhanQuyenGateway { public List<ET_PhanQuyen> LoadDS() => DAL_PhanQuyen.Instance.LoadDS(); public bool Them(ET_PhanQuyen et) => DAL_PhanQuyen.Instance.Them(et); public bool XoaTheoVaiTro(int idVaiTro) => DAL_PhanQuyen.Instance.XoaTheoVaiTro(idVaiTro); }
    internal class DefaultNhaHangGateway : INhaHangGateway { public List<ET_NhaHang> LoadDS() => DAL_NhaHang.Instance.LoadDS(); public bool Them(ET_NhaHang et) => DAL_NhaHang.Instance.Them(et); public bool Sua(ET_NhaHang et) => DAL_NhaHang.Instance.Sua(et); public bool Xoa(int id) => DAL_NhaHang.Instance.Xoa(id); }
    internal class DefaultDanhSachThietBiGateway : IDanhSachThietBiGateway { public List<ET_DanhSachThietBi> LoadDS() => DAL_DanhSachThietBi.Instance.LoadDS(); public List<ET_DanhSachThietBi> LoadDSTheoLoai(string loai) => DAL_DanhSachThietBi.Instance.LoadDSTheoLoai(loai); public List<ET_DanhSachThietBi> TimKiem(string kw, string loai, string tt) => DAL_DanhSachThietBi.Instance.TimKiem(kw, loai, tt); public bool Them(ET_DanhSachThietBi et) => DAL_DanhSachThietBi.Instance.Them(et); public bool Sua(ET_DanhSachThietBi et) => DAL_DanhSachThietBi.Instance.Sua(et); public bool Xoa(int id) => DAL_DanhSachThietBi.Instance.Xoa(id); public bool DoiTrangThai(int id, string tt) => DAL_DanhSachThietBi.Instance.DoiTrangThai(id, tt); }
    internal class DefaultQuyenHanGateway : IQuyenHanGateway { public List<ET_QuyenHan> LoadDS() => DAL_QuyenHan.Instance.LoadDS(); }
    internal class DefaultLichSuDiemGateway : ILichSuDiemGateway { public List<ET_LichSuDiem> LoadDS() => DAL_LichSuDiem.Instance.LoadDS(); public List<ET_LichSuDiem> LayTheoKhachHang(int idKhachHang) => DAL_LichSuDiem.Instance.LayTheoKhachHang(idKhachHang); public bool Them(ET_LichSuDiem et) => DAL_LichSuDiem.Instance.Them(et); }

    // --- Nhóm C Default Gateways ---
    internal class DefaultNhanVienGateway : INhanVienGateway { public List<ET_NhanVien> LoadDS() => DAL_NhanVien.Instance.LoadDS(); public ET_NhanVien LayTheoId(int id) => DAL_NhanVien.Instance.LayTheoId(id); public bool Them(ET_NhanVien et) => DAL_NhanVien.Instance.Them(et); public bool Sua(ET_NhanVien et) => DAL_NhanVien.Instance.Sua(et); public bool Xoa(int id) => DAL_NhanVien.Instance.Xoa(id); public ET_NhanVien DangNhap(string username, string password) => DAL_NhanVien.Instance.DangNhap(username, password); }
    internal class DefaultKhuyenMaiGateway : IKhuyenMaiGateway { public List<ET_KhuyenMai> LoadDS() => DAL_KhuyenMai.Instance.LoadDS(); public bool Them(ET_KhuyenMai et) => DAL_KhuyenMai.Instance.Them(et); public bool Sua(ET_KhuyenMai et) => DAL_KhuyenMai.Instance.Sua(et); public bool Xoa(int id) => DAL_KhuyenMai.Instance.Xoa(id); }
    internal class DefaultSuKienGateway : ISuKienGateway { public List<ET_SuKien> LoadDS() => DAL_SuKien.Instance.LoadDS(); public bool Them(ET_SuKien et) => DAL_SuKien.Instance.Them(et); public bool Sua(ET_SuKien et) => DAL_SuKien.Instance.Sua(et); public bool Xoa(int id) => DAL_SuKien.Instance.Xoa(id); }
    internal class DefaultBangGiaGateway : IBangGiaGateway { public List<ET_BangGia> LayTheoSanPham(int idSanPham) => DAL_BangGia.Instance.LayTheoSanPham(idSanPham); public List<ET_BangGia> LayGiaHienTai(int idSanPham, TimeSpan gio) => DAL_BangGia.Instance.LayGiaHienTai(idSanPham, gio); public bool Them(ET_BangGia et) => DAL_BangGia.Instance.Them(et); public bool Sua(ET_BangGia et) => DAL_BangGia.Instance.Sua(et); public bool Xoa(int id) => DAL_BangGia.Instance.Xoa(id); }
    internal class DefaultCauHinhNgayLeGateway : ICauHinhNgayLeGateway { public bool LaNgayLe(DateTime ngay) => DAL_CauHinhNgayLe.Instance.LaNgayLe(ngay); }
    internal class DefaultQuyDoiDonViGateway : IQuyDoiDonViGateway { public List<ET_QuyDoiDonVi> LoadDS() => DAL_QuyDoiDonVi.Instance.LoadDS(); public bool Them(ET_QuyDoiDonVi et) => DAL_QuyDoiDonVi.Instance.Them(et); public bool Sua(ET_QuyDoiDonVi et) => DAL_QuyDoiDonVi.Instance.Sua(et); public bool Xoa(int id) => DAL_QuyDoiDonVi.Instance.Xoa(id); }
    internal class DefaultQuyTacDiemGateway : IQuyTacDiemGateway { public List<ET_QuyTacDiem> LoadDS() => DAL_QuyTacDiem.Instance.LoadDS(); public List<ET_QuyTacDiem> LayQuyTacActive() => DAL_QuyTacDiem.Instance.LayQuyTacActive(); }
    internal class DefaultThueDoChiTietGateway : IThueDoChiTietGateway { public List<ET_ThueDoChiTiet> LoadDS() => DAL_ThueDoChiTiet.Instance.LoadDS(); public bool Them(ET_ThueDoChiTiet et) => DAL_ThueDoChiTiet.Instance.Them(et); public bool Sua(ET_ThueDoChiTiet et) => DAL_ThueDoChiTiet.Instance.Sua(et); public ET_ThueDoChiTiet LayTheoId(int id) => DAL_ThueDoChiTiet.Instance.LayTheoId(id); }

    // --- BUS-to-BUS Interfaces ---
    public interface IBUS_GiaoDichVi {
        ET.OperationResult DongBangTienVi(string maRfid, decimal soTienDongBang, int? idDonHang = null);
        ET.OperationResult GiaiToaTienCoc(int idKhachHang, decimal soTien, int? idDonHang = null);
        ET.OperationResult KhauTruTienDongBang(int idKhachHang, decimal soTien, int? idDonHang = null);
        ET.OperationResult<ET.ET_ViDienTu> TraCuuViTheoRFID(string maRfid);
    }

    public interface IBUS_DoanKhach {
        ET.ET_DoanKhach_DichVu LayQuotaTheoLoai(int idDoan, string loaiDichVu);
    }
}
