import re

files = [
    r"c:\Users\ADMIN\Desktop\DaiNamNew\GUI\Modules\BanHang\ucGiaoDo.Designer.cs",
    r"c:\Users\ADMIN\Desktop\DaiNamNew\GUI\Modules\BanHang\ucNhanTra.Designer.cs",
    r"c:\Users\ADMIN\Desktop\DaiNamNew\GUI\Modules\BanHang\frmPhatMatDo.Designer.cs"
]

for f in files:
    with open(f, "r", encoding="utf-8") as file:
        lines = file.readlines()
    
    new_lines = []
    for line in lines:
        # Regex to match custom comments like:
        # // --- Panel trái...
        # // ===== splitMain...
        # // txtBarcode
        # But NOT match: // (empty comment line generated by VS sometimes)
        if re.match(r"^\s*//\s+[-=A-Za-z]+", line):
            continue
        new_lines.append(line)
        
    with open(f, "w", encoding="utf-8") as file:
        file.writelines(new_lines)
    print(f"Cleaned {f}")
