import json

translations = {
    'ERR_COMBO_CHUA_LUU': ('Vui lòng Lưu Combo trước!', 'Please save the Combo first!', '请先保存套餐！'),
    'ERR_CTK_DA_DUYET': ('Phiếu này đã được duyệt và khóa sổ.', 'This voucher has been approved and locked.', '此单据已批准并锁定。'),
    'ERR_DUP_CODE': ("Mã sản phẩm '{0}' đã tồn tại trên hệ thống.", "Product code '{0}' already exists.", "产品代码 '{0}' 已存在。"),
    'ERR_EMPTY_CODE': ('Mã sản phẩm không được bỏ trống.', 'Product code cannot be empty.', '产品代码不能为空。'),
    'ERR_EMPTY_NAME': ('Tên sản phẩm không được bỏ trống.', 'Product name cannot be empty.', '产品名称不能为空。'),
    'ERR_EMPTY_TYPE': ('Vui lòng chọn loại sản phẩm.', 'Please select product type.', '请选择产品类型。'),
    'ERR_EMPTY_UNIT': ('Vui lòng chọn đơn vị tính.', 'Please select unit of measurement.', '请选择计量单位。'),
    'ERR_LOHANG_TEN_RONG': ('Tên lô hàng không được để trống', 'Batch name cannot be empty', '批次名称不能为空'),
    'ERR_PHANQUYEN_FAIL': ('Cập nhật thất bại. Vui lòng thử lại!', 'Update failed. Please try again!', '更新失败。请重试！'),
    'ERR_POS_CHUA_MO_PHIEN': ('Chưa mở phiên thu ngân. Vui lòng mở phiên trước khi bán hàng.', 'Cashier session not open. Please open session before selling.', '收银班次未开启。销售前请开启班次。'),
    'ERR_POS_GIO_RONG': ('Giỏ hàng đang trống, không có gì để thanh toán.', 'Cart is empty, nothing to checkout.', '购物车为空，没有需要结算的商品。'),
    'ERR_POS_PHIEN_DANG_MO': ('Máy POS này đang có phiên mở bởi người khác.', 'This POS has an open session by another user.', '该POS机已有其他人开启的班次。'),
    'ERR_POS_RFID_KHONGTIMTHAY': ("Không tìm thấy thẻ RFID '{0}' trên hệ thống.", "RFID card '{0}' not found in the system.", "系统中未找到RFID卡 '{0}'。"),
    'ERR_POS_RFID_KHONG_DU': ('Số dư ví RFID không đủ để thanh toán khoản này.', 'RFID wallet balance is insufficient for this payment.', 'RFID钱包余额不足以支付此款项。'),
    'ERR_POS_SOLUONG_AM': ('Số lượng phải lớn hơn 0.', 'Quantity must be greater than 0.', '数量必须大于0。'),
    'ERR_POS_SP_KHONGTIMTHAY': ("Không tìm thấy sản phẩm với mã '{0}'.", "Product with code '{0}' not found.", "未找到代码为 '{0}' 的产品。"),
    'ERR_POS_TIEN_KHONG_KHOP': ('Tổng tiền thanh toán chưa khớp với tổng bill. Vui lòng kiểm tra lại.', 'Total payment does not match the bill. Please check again.', '支付总额与账单总额不符。请重新检查。'),
    'ERR_REFUND_NO_ITEMS': ('Vui lòng nhập định mức cần hoàn cho ít nhất 1 sản phẩm!', 'Please enter refund amount for at least 1 product!', '请为至少1个产品输入退款金额！'),
    'ERR_TICKET_NO_GATE': ('Sản phẩm loại Vé bắt buộc thiết lập ít nhất 1 quyền quẹt thẻ.', 'Ticket product requires at least 1 gate access right.', '门票类产品必须至少设置1个刷卡权限。'),
    'FILTER_ALL': ('Tất cả', 'All', '全部'),
    'FILTER_CHOTHUE': ('Cho Thuê', 'Rental', '出租'),
    'FILTER_DOAN': ('Đồ Ăn', 'Food', '食品'),
    'FILTER_DOUONG': ('Đồ Uống', 'Beverage', '饮料'),
    'FILTER_LUUTRU': ('Lưu Trú', 'Accommodation', '住宿'),
    'FILTER_VATTU': ('Vật Tư', 'Supplies', '物资'),
    'FILTER_VE': ('Vé', 'Ticket', '门票'),
    'FNB_CAT_ANVAT': ('Ăn vặt', 'Snacks', '小吃'),
    'FNB_CAT_CHAY': ('Đồ chay', 'Vegetarian', '素食'),
    'FNB_CAT_KHAIVI': ('Khai vị', 'Appetizers', '开胃菜'),
    'FNB_CAT_MONCHINH': ('Món chính', 'Main Course', '主菜'),
    'FNB_CAT_NUOC': ('Nước uống', 'Drinks', '饮品'),
    'FNB_CAT_TRANGMIENG': ('Tráng miệng', 'Dessert', '甜点'),
    'FRM_COMBO_TITLE': ('QUẢN LÝ COMBO SẢN PHẨM', 'PRODUCT COMBO MANAGEMENT', '产品套餐管理'),
    'GRID_COL_DVT': ('ĐVT', 'Unit', '单位'),
    'GRID_COL_HANH_DONG': ('Hành Động', 'Action', '操作'),
    'GRID_COL_LOAISP': ('Loại SP', 'Product Type', '产品类型'),
    'GRID_COL_MASP': ('Mã SP', 'Product Code', '产品代码'),
    'GRID_COL_TENSP': ('Tên Sản Phẩm', 'Product Name', '产品名称'),
    'KHACH_TRA': ('Khách trả hàng', 'Customer Return', '客户退货'),
    'KimCuongDiamond': ('Kim Cương', 'Diamond', '钻石'),
    'LBL_DIEM_BAN': ('Điểm bán (POS)', 'Point of Sale (POS)', '销售点 (POS)'),
    'LBL_DVT': ('Đơn vị tính (*)', 'Unit of Measurement (*)', '计量单位 (*)'),
    'LBL_GHICHU': ('Ghi Chú:', 'Note:', '备注:'),
    'LBL_GIA_UU_TIEN': ('Giá ưu tiên', 'Priority Price', '优先价格'),
    'LBL_GRID_TITLE_FNB': ('Định mức nguyên liệu (R&D BOM):', 'Material Quota (R&D BOM):', '材料定额 (R&D BOM):'),
    'LBL_KHU_VUC': ('Khu vực', 'Area', '区域'),
    'LBL_KH_CCCD': ('CCCD', 'ID Card', '身份证'),
    'LBL_KH_DIACHI': ('Địa chỉ', 'Address', '地址'),
    'LBL_KH_DIEM': ('Điểm tích lũy', 'Accumulated Points', '累计积分'),
    'LBL_KH_EMAIL': ('Email', 'Email', '电子邮件'),
    'LBL_KH_FIELD_CCCD': ('CCCD / CMND', 'ID Card / Passport', '身份证 / 护照'),
    'LBL_KH_FIELD_DIACHI': ('Địa chỉ', 'Address', '地址'),
    'LBL_KH_FIELD_EMAIL': ('Email', 'Email', '电子邮件'),
    'LBL_KH_FIELD_HANG': ('Hạng thành viên', 'Membership Tier', '会员等级'),
    'LBL_KH_FIELD_MA': ('Mã khách hàng', 'Customer Code', '客户代码'),
    'LBL_KH_FIELD_NGAYTAO': ('Ngày đăng ký', 'Registration Date', '注册日期'),
    'LBL_KH_FIELD_SDT': ('Số điện thoại', 'Phone Number', '电话号码'),
    'LBL_KH_HANG': ('Hạng thành viên', 'Membership Tier', '会员等级'),
    'LBL_KH_LOAI': ('Loại khách', 'Customer Type', '客户类型'),
    'LBL_KH_MA': ('Mã KH', 'Cust Code', '客户代码'),
    'LBL_KH_SDT': ('Điện thoại (*)', 'Phone (*)', '电话 (*)'),
    'LBL_KH_SODU': ('Số dư khả dụng', 'Available Balance', '可用余额'),
    'LBL_KH_TEN': ('Họ tên (*)', 'Full Name (*)', '姓名 (*)'),
    'LBL_KH_THE_RFID': ('Thẻ RFID', 'RFID Card', 'RFID卡'),
    'LBL_KH_TONGCHI': ('Tổng chi tiêu', 'Total Spending', '总消费'),
    'LBL_LOAIPHIEU': ('Loại Phiếu:', 'Voucher Type:', '单据类型:'),
    'LBL_LOAISP': ('Loại sản phẩm (*)', 'Product Type (*)', '产品类型 (*)'),
    'LBL_MAPHIEU': ('Mã Phiếu:', 'Voucher Code:', '单据代码:'),
    'LBL_MASP': ('Mã sản phẩm (*)', 'Product Code (*)', '产品代码 (*)'),
    'LBL_NCC': ('Nhà Cung Cấp:', 'Supplier:', '供应商:'),
    'LBL_NGAYLAP': ('Ngày Lập:', 'Creation Date:', '创建日期:'),
    'LBL_NHA_HANG': ('Bếp / Bar phụ trách:', 'Kitchen / Bar in charge:', '负责厨房 / 吧台:'),
    'LBL_PHAN_LOAI_FNB': ('Phân loại thêm:', 'Additional Category:', '附加分类:'),
    'LBL_QUYENHAN_TITLE': ('Phân quyền (Hierarchy Tree)', 'Permissions (Hierarchy Tree)', '权限 (层级树)'),
    'LBL_TITLE_FNB': ('Dành riêng cho: ĐỒ ĂN & THỨC UỐNG', 'Exclusive for: FOOD & BEVERAGE', '专用于：食品与饮料'),
    'LBL_VAITRO_TITLE': ('Chọn Vai Trò', 'Select Role', '选择角色'),
    'LBL_VAT': ('Thuế VAT', 'VAT Tax', '增值税'),
    'LOAIGIA_KHUYENMAI': ('Khuyến mãi', 'Promotion', '促销'),
    'LOAIGIA_MACDINH': ('Mặc định', 'Default', '默认'),
    'LOAIGIA_NGAYLE': ('Ngày lễ', 'Holiday', '节假日'),
    'LOAISP_ANUONG': ('Đồ ăn', 'Food', '食品'),
    'LOAISP_CHOINGHIMAT': ('Chòi nghỉ mát', 'Gazebo', '凉亭'),
    'LOAISP_DATCHOTHUAN': ('Đặt chỗ thú ăn', 'Animal Feeding Prep', '动物喂食准备'),
    'LOAISP_DOCHO': ('Đồ cho thuê', 'Rental Item', '出租物品'),
    'LOAISP_DOUONG': ('Đồ uống', 'Beverage', '饮料'),
    'LOAISP_GUIXE': ('Gửi xe (Bãi xe định mức)', 'Parking', '停车'),
    'LOAISP_HANGHOA': ('Hàng hoá chung', 'General Goods', '普通商品'),
    'LOAISP_LUUTRU': ('Lưu trú (Phòng)', 'Accommodation (Room)', '住宿 (房间)'),
    'LOAISP_NGUYENLIEU': ('Nguyên liệu', 'Material', '原料'),
    'LOAISP_TUDO': ('Tủ đồ (Giữ đồ)', 'Locker', '储物柜'),
    'LOAISP_VETROCHOI': ('Vé trò chơi', 'Game Ticket', '游戏票'),
    'LOAISP_VEVAOKHU': ('Vé vào khu', 'Entrance Ticket', '门票'),
    'MENU_GRP_DANHMUC': ('Hệ thống Danh Mục', 'Category System', '目录系统'),
    'MENU_GRP_DASHBOARD': ('Bảng điều khiển', 'Dashboard', '仪表板'),
    'MENU_GRP_DOITAC': ('Quản trị', 'Administration', '管理'),
    'MENU_GRP_POS': ('Bán hàng', 'Sales', '销售'),
    'MENU_ITEM_COMBO': ('Quản lý Combo', 'Combo Management', '套餐管理'),
    'MENU_ITEM_DASHBOARD': ('Thống kê tổng quan', 'Overview Statistics', '概览统计'),
    'MENU_ITEM_SANPHAM': ('Sản phẩm, Dịch vụ & Vé', 'Products, Services & Tickets', '产品、服务与门票'),
    'MNU_XOADONG': ('Xóa dòng', 'Delete row', '删除行'),
    'MSG_CTK_XOA_OK': ('Xoá phiếu thành công.', 'Voucher deleted successfully.', '单据删除成功。'),
    'MSG_DIEM_CONG_OK': ('Cộng điểm thành công!', 'Points added successfully!', '积分添加成功！'),
    'MSG_DIEM_TRU_OK': ('Trừ điểm thành công!', 'Points deducted successfully!', '积分扣除成功！'),
    'MSG_GIU_XOA_OK': ('Thả tự do lượng hàng hoá thành công', 'Goods released successfully', '货物释放成功'),
    'MSG_KH_LUU_OK': ('Lưu thông tin khách hàng thành công!', 'Customer information saved successfully!', '客户信息保存成功！'),
    'MSG_KH_XOA_OK': ('Xóa khách hàng thành công!', 'Customer deleted successfully!', '客户删除成功！'),
    'MSG_LOHANG_LUU_OK': ('Cập nhật lô hàng thành công', 'Batch updated successfully', '批次更新成功'),
    'MSG_LUU_RO_OK': ('Lưu rổ combo thành công!', 'Combo basket saved successfully!', '套餐篮保存成功！'),
    'MSG_NAP_TIEN_OK': ('Nạp tiền vào ví thành công!', 'Money added to wallet successfully!', '钱包充值成功！'),
    'MSG_PHANQUYEN_SUCCESS': ('Cập nhật phân quyền thành công!', 'Permissions updated successfully!', '权限更新成功！'),
    'MSG_POS_CHECKOUT_OK': ('Thanh toán đơn hàng thành công.', 'Order checkout successful.', '订单结账成功。'),
    'MSG_POS_PHIEN_DONG_OK': ('Đóng phiên thu ngân thành công.', 'Cashier session closed successfully.', '收银班次关闭成功。'),
    'MSG_POS_PHIEN_MO_OK': ('Mở phiên thu ngân thành công.', 'Cashier session opened successfully.', '收银班次开启成功。'),
    'MSG_RFID_KICH_HOAT_OK': ('Kích hoạt/cấp thẻ thành công!', 'Card activated/issued successfully!', '卡激活/发放成功！'),
    'NULL_DOITAC': ('-- Chọn Đối Tác --', '-- Select Partner --', '-- 选择合作伙伴 --'),
    'PAY_USE_POINTS': ('Dùng {0} điểm (khấu trừ {1}₫)', 'Use {0} points (deduct {1}₫)', '使用 {0} 积分 (扣除 {1}₫)'),
    'POS_LBL_CA': ('Ca:', 'Shift:', '班次:'),
    'POS_LBL_CASHIER': ('Thu ngân', 'Cashier', '收银员'),
    'POS_LBL_GIAMGIA': ('Giảm giá:', 'Discount:', '折扣:'),
    'POS_LBL_GIOHANG': ('GIỎ HÀNG', 'SHOPPING CART', '购物车'),
    'POS_LBL_MACHINE': ('Máy', 'Machine', '机器'),
    'POS_LBL_SESSION': ('Phiên', 'Session', '班次'),
    'POS_LBL_SHIFT': ('Ca', 'Shift', '班次'),
    'POS_LBL_THUEVAT': ('Thuế VAT:', 'VAT Tax:', '增值税:'),
    'POS_LBL_THUNGAN': ('Thu ngân:', 'Cashier:', '收银员:'),
    'POS_LBL_TIENHANG': ('Tiền hàng:', 'Subtotal:', '小计:'),
    'POS_MSG_XOAGIO': ('Xóa toàn bộ giỏ hàng? Hành động này không thể hoàn tác.', 'Clear entire cart? This action cannot be undone.', '清空整个购物车？此操作无法撤销。'),
    'POS_PHIEN_BTN_CHOT': ('Chốt ca', 'Close Shift', '结账关班'),
    'POS_PHIEN_BTN_MO': ('Mở phiên', 'Open Session', '开启班次'),
    'POS_PHIEN_LBL_CHENHLECH': ('Chênh lệch:', 'Difference:', '差额:'),
    'POS_PHIEN_LBL_MAYPOS': ('Máy POS:', 'POS Machine:', 'POS机:'),
    'POS_PHIEN_LBL_MOLUC': ('Mở lúc:', 'Opened At:', '开启时间:'),
    'POS_PHIEN_LBL_TIENCUOICA': ('Tiền cuối ca (đếm tay):', 'End Cash (Manual Count):', '期末现金 (人工清点):'),
    'POS_PHIEN_LBL_TIENDAUCA': ('Tiền đầu ca:', 'Starting Cash:', '期初现金:'),
    'POS_PHIEN_LBL_TONGTHU': ('Tổng thu trong ca:', 'Total shift revenue:', '班次总收入:'),
    'POS_PHIEN_TITLE_DONG': ('Đóng phiên thu ngân', 'Close Cashier Session', '关闭收银班次'),
    'POS_PHIEN_TITLE_MO': ('Mở phiên thu ngân', 'Open Cashier Session', '开启收银班次'),
    'POS_STATUS_MAY': ('Máy:', 'Machine:', '机器:'),
    'POS_STATUS_PHIEN': ('Phiên', 'Session', '班次'),
    'POS_TAB_HANGHOA': ('Hàng hóa', 'Goods', '商品'),
    'POS_TAB_THUEDO': ('Thuê đồ', 'Rental', '出租'),
    'POS_TAB_VE': ('Vé', 'Ticket', '门票'),
    'POS_TOAST_THANHCONG': ('Thanh toán thành công', 'Payment Successful', '付款成功'),
    'POS_TOAST_TIENTHUA': ('Tiền thừa: {0}', 'Change: {0}', '找零: {0}'),
    'POS_TOAST_VENAPHAT': ('{0} mã QR vé đã phát', '{0} ticket QR codes issued', '已发放 {0} 个门票二维码'),
    'POS_TT_BTN_THEMDONG': ('+ Thêm dòng thanh toán', '+ Add payment line', '+ 添加付款行'),
    'POS_TT_BTN_VUADU': ('Vừa đủ', 'Exact Amount', '金额刚好'),
    'POS_TT_BTN_XACNHAN': ('Xác nhận', 'Confirm', '确认'),
    'POS_TT_COL_MATHERFID': ('Mã thẻ RFID', 'RFID Code', 'RFID代码'),
    'POS_TT_COL_PHUONGTHUC': ('Phương thức', 'Method', '付款方式'),
    'POS_TT_COL_SOTIEN': ('Số tiền', 'Amount', '金额'),
    'POS_TT_CONTHIEU': ('Còn thiếu:', 'Remaining:', '尚欠:'),
    'POS_TT_DATRA': ('Đã trả:', 'Paid:', '已付:'),
    'POS_TT_LBL_CHUTHE': ('Chủ thẻ:', 'Cardholder:', '持卡人:'),
    'POS_TT_LBL_SAUTRU': ('Sau trừ:', 'After deduct:', '扣除后:'),
    'POS_TT_LBL_SODU': ('Số dư ví:', 'Wallet Balance:', '钱包余额:'),
    'POS_TT_TIENTHUA': ('Tiền thừa:', 'Change:', '找零:'),
    'POS_TT_TITLE': ('Thanh toán', 'Payment', '付款'),
    'POS_WATERMARK_BARCODE': ('Quét mã hoặc gõ tên sản phẩm...', 'Scan barcode or type product name...', '扫描条形码或输入产品名称...'),
    'PROMPT_TIM_KIEM': ('Chỉ nhập từ khóa để tìm kiếm...', 'Enter keyword to search...', '输入关键字以搜索...'),
    'PTTT_MOMO': ('MoMo', 'MoMo', 'MoMo'),
    'PTTT_QR': ('QR Code', 'QR Code', '二维码'),
    'PTTT_THENGANH': ('Thẻ ngân hàng', 'Bank Card', '银行卡'),
    'REFUND_BTN_CONFIRM': ('XÁC NHẬN HOÀN', 'CONFIRM REFUND', '确认退款'),
    'REFUND_COL_BOUGHT': ('Đã Mua', 'Bought', '已购买'),
    'REFUND_COL_PRICE': ('Đơn Giá / Mức Phạt', 'Price / Penalty', '单价/罚金'),
    'REFUND_COL_PRODUCT': ('Sản Phẩm', 'Product', '产品'),
    'REFUND_COL_REASON': ('Lý Do', 'Reason', '原因'),
    'REFUND_COL_REFUNDED': ('Đã Hoàn', 'Refunded', '已退款'),
    'REFUND_COL_RETURNQTY': ('SL Muốn Hoàn', 'Return Qty', '欲退数量'),
    'REFUND_COL_TYPE': ('Loại', 'Type', '类型'),
    'REFUND_SEARCH_HINT': ('Mã Đơn Hàng cần hoàn...', 'Order Code to refund...', '需要退款的订单代码...'),
    'REFUND_TITLE': ('Nghiệp Vụ - Hoàn Trả Giao Dịch Bán Lẻ', 'Retail Refund Operation', '零售退款操作'),
    'TAB_BANG_GIA': ('Bảng giá', 'Price List', '价格表'),
    'TAB_CAU_HINH': ('Cấu hình vận hành', 'Operation Config', '运行配置'),
    'TAB_KH_DIEM': ('Lịch sử điểm', 'Points History', '积分历史'),
    'TAB_KH_LICHSU': ('Lịch sử GD', 'Transaction History', '交易历史'),
    'TAB_KH_LICHSU_GD': ('Lịch sử giao dịch', 'Transaction History', '交易历史'),
    'TAB_KH_THE_VI': ('Thẻ & Ví', 'Cards & Wallets', '卡与钱包'),
    'TAB_KH_THONGTIN': ('Thông tin', 'Information', '信息'),
    'TAB_QUY_DOI': ('Quy đổi ĐVT', 'Unit Conversion', '单位换算'),
    'TAB_THONG_TIN': ('Thông tin chung', 'General Info', '基本信息'),
    'TITLE_CANHBAO': ('Cảnh báo mất dữ liệu', 'Data Loss Warning', '数据丢失警告'),
    'TITLE_REFUND_CONFIRM': ('Hoàn Khách Hàng', 'Refund to Customer', '向客户退款'),
    'TITLE_SUA_SP': ('Chỉnh sửa sản phẩm', 'Edit Product', '编辑产品'),
    'TITLE_THEM_SP': ('Thêm sản phẩm mới', 'Add New Product', '添加新产品'),
    'TITLE_UNSAVED': ('Cảnh báo mất dữ liệu', 'Data Loss Warning', '数据丢失警告'),
    'TOOLTIP_GIAUUTIEN': ('Giá này là thông tin chỉ đọc. Vui lòng chuyển sang Tab [Bảng giá] để lên lịch thiết lập giá bán mới.', 'This price is read-only. Please go to [Price List] Tab to schedule new pricing.', '此价格为只读信息。请切换到[价格表]选项卡以安排新的定价。'),
    'TRANGTHAI_DANGBAN': ('Đang bán', 'Selling', '在售'),
    'TRANGTHAI_HOATDONG': ('Hoạt động', 'Active', '激活'),
    'TRANGTHAI_NGUNGBAN': ('Ngừng bán', 'Discontinued', '停售'),
    'TRANGTHAI_NGUNGHOATDONG': ('Ngưng hoạt động', 'Inactive', '停用'),
    'TRANGTHAI_TAMNGUNG': ('Tạm ngưng', 'Suspended', '暂停'),
    'TXT_ALERT_HSD': ('0 Lô sắp hết HSD', '0 Batches expiring soon', '0 个批次即将过期'),
    'AI_TITLE': ('AI Assistant', 'AI Assistant', 'AI 助手'),
    'AI_SETTINGS_TITLE': ('AI Settings', 'AI Settings', 'AI 设置'),
    'AI_SETTINGS_APIKEY': ('Gemini API Key:', 'Gemini API Key:', 'Gemini API 密钥:'),
    'AI_SETTINGS_MODEL': ('Model:', 'Model:', '模型:'),
    'AI_SETTINGS_TEST': ('Test Connection', 'Test Connection', '测试连接'),
    'BTN_DONG': ('ĐÓNG', 'CLOSE', '关闭'),
    'BTN_HUY': ('Hủy (Esc)', 'Cancel (Esc)', '取消 (Esc)'),
    'BTN_LAMMOI': ('LÀM MỚI', 'REFRESH', '刷新'),
    'BTN_LAM_MOI': ('Làm Mới', 'Refresh', '刷新'),
    'BTN_LUU': ('Lưu (F2)', 'Save (F2)', '保存 (F2)'),
    'BTN_SUA': ('Sửa', 'Edit', '编辑'),
    'BTN_THEM': ('Thêm Mới', 'Add New', '新增'),
    'BTN_THEM_DONG': ('+ Thêm dòng', '+ Add row', '+ 添加行'),
    'BTN_THEM_MOI': ('Thêm mới', 'Add New', '新增'),
    'BTN_THEM_NGUYEN_LIEU': ('Thêm nguyên liệu', 'Add material', '添加材料'),
    'BTN_XOA': ('Xóa', 'Delete', '删除'),
    'BacSilver': ('Bạc', 'Silver', '白银'),
    'CHK_ALL_POS': ('Áp dụng cho tất cả điểm bán', 'Apply to all POS', '应用于所有销售点'),
    'CHK_DI_UNG': ('Món ăn chứa thành phần dễ bề dị ứng', 'Dish contains allergens', '菜品含有过敏原'),
    'COL_DVT': ('ĐVT Gốc', 'Base Unit', '基本单位'),
    'COL_DVT_DICH': ('ĐVT Đích', 'Target Unit', '目标单位'),
    'COL_GIABAN': ('Giá bán', 'Selling Price', '售价'),
    'COL_GIAPHUTHU': ('Giá phụ thu', 'Surcharge Price', '附加费'),
    'COL_HESO': ('Hệ số quy đổi', 'Conversion Ratio', '转换率'),
    'COL_HIEULUC_DEN': ('Hiệu lực đến', 'Valid Until', '有效期至'),
    'COL_HIEULUC_TU': ('Hiệu lực từ', 'Valid From', '生效日期'),
    'COL_LECH': ('Lệch', 'Diff', '差异'),
    'COL_LOAIGIA': ('Phân loại', 'Category', '分类'),
    'COL_MAHANG': ('Mã Hàng', 'Item Code', '商品代码'),
    'COL_MA_KHU_VUC': ('Mã KV', 'Area Code', '区域代码'),
    'COL_NGUYEN_LIEU': ('Vật tư / Nguyên liệu', 'Material / Ingredient', '物料 / 原料'),
    'COL_PHUTBLOCK': ('Block (phút)', 'Block (min)', '计费块 (分钟)'),
    'COL_PHUTTIEP': ('Phút tiếp', 'Next min', '下一分钟'),
    'COL_SO_LUONG': ('Số lượng', 'Quantity', '数量'),
    'COL_TENHANG': ('Tên Hàng', 'Item Name', '商品名称'),
    'COL_TEN_KHU_VUC': ('Tên khu vực', 'Area Name', '区域名称'),
    'COL_TIENCOC': ('Tiền cọc', 'Deposit', '押金'),
    'COL_TONMAY': ('Tồn Máy', 'System Stock', '系统库存'),
    'COL_TRANG_THAI': ('Trạng thái', 'Status', '状态'),
    'CTX_CHEN_DONG': ('Chèn dòng mới', 'Insert new row', '插入新行'),
    'CTX_HUY_PHIEU': ('Hủy phiếu', 'Cancel voucher', '取消单据'),
    'CTX_IN_PHIEU': ('In phiếu', 'Print voucher', '打印单据'),
    'CTX_MO_PHIEU': ('Mở phiếu xem chi tiết', 'Open voucher details', '打开单据详情'),
    'CTX_MO_PHIEU_GOC': ('Mở phiếu gốc', 'Open original voucher', '打开原始单据'),
    'CTX_SAO_CHEP': ('Sao chép làm phiếu mới', 'Copy as new voucher', '复制为新单据'),
    'CTX_SAO_DONG': ('Sao chép dòng', 'Copy row', '复制行'),
    'CTX_TAO_PHIEU_XUAT': ('Tạo phiếu xuất cho SP này', 'Create issue voucher for this item', '为此产品创建出库单'),
    'CTX_THIET_LAP_MUC_CB': ('Thiết lập mức cảnh báo', 'Set warning level', '设置预警级别'),
    'CTX_XEM_LICHSU': ('Xem lịch sử SP này', 'View history for this item', '查看此产品历史'),
    'CTX_XOA_DONG': ('Xóa dòng này', 'Delete this row', '删除此行'),
    'CTX_XUAT_EXCEL': ('Xuất Excel', 'Export Excel', '导出Excel'),
    'POS_TAB_FNB': ('F&B', 'F&B', '餐饮'),
    'BTN_KH_MO_THE': ('Mở thẻ', 'Issue Card', '发卡'),
    'BTN_KH_NAP_TIEN': ('Nạp tiền ví', 'Top Up Wallet', '钱包充值'),
    'COL_DEMTHUCTE': ('Đếm / Nhập', 'Count / Input', '清点 / 输入')
}

import re
file_path = r'c:\Users\ADMIN\Desktop\DaiNamNew\GUI\Properties\UpdateResx.cs'
with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

# Replace any new {...} block that has these keys with the EXACT translations provided above
for key, (vi, en, zh) in translations.items():
    pattern = re.compile(rf'new\s*\{{\s*Key\s*=\s*"{key}",\s*Vi\s*=\s*"[^"]*",\s*En\s*=\s*"[^"]*",\s*Zh\s*=\s*"[^"]*"\s*\}}')
    repl = f'new {{ Key = "{key}", Vi = "{vi}", En = "{en}", Zh = "{zh}" }}'
    content = pattern.sub(repl, content)

with open(file_path, 'w', encoding='utf-8') as f:
    f.write(content)

print("Full dictionary translations applied.")
