import csv

tcs = [
    ["UC_PQ_001","TC_PQ_014","Giao diện cây phân quyền khi chưa chọn vai trò","5","UI/UX","3.1 Màn hình thiết lập phân quyền","Hệ thống đang chạy bình thường.","Bước 1. Mở phần mềm Đại Nam POS.\nBước 2. Đăng nhập tài khoản Quản trị viên (admin).\nBước 3. Vào Hệ thống, chọn Phân quyền.\nBước 4. Quan sát cây phân quyền bên phải khi danh sách bên trái chưa được chọn dòng nào.","Bước 1. Phần mềm khởi động, hiển thị màn hình đăng nhập.\nBước 2. Đăng nhập thành công, vào màn hình chính.\nBước 3. Màn hình phân quyền mở ra.\nBước 4. Cây phân quyền bên phải không hiển thị tích chọn nào, hoặc bị mờ đi cho đến khi chọn vai trò.","Medium","","","Bùi Trí Nguyên",""],
    
    ["UC_PQ_001","TC_PQ_015","Hiển thị đa ngôn ngữ - Tiếng Anh","5","UI/UX","3.1 Màn hình thiết lập phân quyền","Hệ thống đang chạy bình thường, tài khoản có quyền đổi ngôn ngữ.","Bước 1. Mở phần mềm Đại Nam POS.\nBước 2. Đăng nhập tài khoản Quản trị viên (admin).\nBước 3. Tại thanh trạng thái (hoặc menu Hệ thống), đổi ngôn ngữ sang Tiếng Anh (English).\nBước 4. Vào Hệ thống, chọn Phân quyền.","Bước 1. Phần mềm khởi động, hiển thị màn hình đăng nhập.\nBước 2. Đăng nhập thành công, vào màn hình chính.\nBước 3. Giao diện chuyển sang Tiếng Anh.\nBước 4. Tiêu đề form, tên nút (Save, Refresh), cột danh mục quyền và các nhóm quyền trên cây đều được dịch sang Tiếng Anh tương ứng.","High","","","Bùi Trí Nguyên",""],
    
    ["UC_PQ_001","TC_PQ_016","Hiển thị đa ngôn ngữ - Tiếng Trung","5","UI/UX","3.1 Màn hình thiết lập phân quyền","Hệ thống đang chạy bình thường.","Bước 1. Mở phần mềm Đại Nam POS.\nBước 2. Đăng nhập tài khoản Quản trị viên (admin).\nBước 3. Tại thanh trạng thái, đổi ngôn ngữ sang Tiếng Trung (中文).\nBước 4. Vào Hệ thống, chọn Phân quyền.","Bước 1. Phần mềm khởi động, hiển thị màn hình đăng nhập.\nBước 2. Đăng nhập thành công, vào màn hình chính.\nBước 3. Giao diện chuyển sang Tiếng Trung.\nBước 4. Màn hình phân quyền hiển thị đúng font chữ, không bị vỡ layout, các từ khóa được dịch sang Tiếng Trung.","High","","","Bùi Trí Nguyên",""],
    
    ["UC_PQ_003","TC_PQ_017","Nhấn nút Làm mới khi không có thay đổi nào","5","Functional","3.3 Cập nhật quyền","Hệ thống đang chạy bình thường.","Bước 1. Mở phần mềm Đại Nam POS.\nBước 2. Đăng nhập tài khoản Quản trị viên (admin).\nBước 3. Vào Hệ thống, chọn Phân quyền.\nBước 4. Nhấn chọn vai trò Quản lý.\nBước 5. Nhấn nút Làm mới.","Bước 1. Phần mềm khởi động, hiển thị màn hình đăng nhập.\nBước 2. Đăng nhập thành công, vào màn hình chính.\nBước 3. Màn hình phân quyền mở ra.\nBước 4. Cây phân quyền hiển thị quyền của Quản lý.\nBước 5. Dữ liệu nháy nhẹ, tải lại danh sách vai trò và cây phân quyền giữ nguyên trạng thái như bước 4.","Low","","","Bùi Trí Nguyên",""],
    
    ["UC_PQ_001","TC_PQ_018","Phân quyền truy cập màn hình - Tài khoản Quản lý","5","Edge Case","3.1 Màn hình thiết lập phân quyền","Tài khoản Quản lý (manager) đang hoạt động và không có quyền Thiết lập Phân quyền.","Bước 1. Mở phần mềm Đại Nam POS.\nBước 2. Đăng nhập tài khoản Quản lý (manager).\nBước 3. Tìm menu Hệ thống trên thanh điều hướng bên trái.\nBước 4. Tìm mục Phân quyền.","Bước 1. Phần mềm khởi động, hiển thị màn hình đăng nhập.\nBước 2. Đăng nhập thành công, vào màn hình chính.\nBước 3. Menu bên trái hiển thị.\nBước 4. Mục Phân quyền bị ẩn hoàn toàn (hoặc nếu hiển thị thì nhấn vào sẽ báo lỗi từ chối truy cập).","High","","","Bùi Trí Nguyên",""],
    
    ["UC_PQ_001","TC_PQ_019","Phân quyền truy cập màn hình - Tài khoản Thu ngân","5","Edge Case","3.1 Màn hình thiết lập phân quyền","Tài khoản Thu ngân (cashier) đang hoạt động.","Bước 1. Mở phần mềm Đại Nam POS.\nBước 2. Đăng nhập tài khoản Thu ngân (cashier).\nBước 3. Quan sát thanh điều hướng bên trái.","Bước 1. Phần mềm khởi động, hiển thị màn hình đăng nhập.\nBước 2. Đăng nhập thành công, vào màn hình chính.\nBước 3. Menu Hệ thống không hiển thị hoặc mục Phân quyền bị ẩn hoàn toàn.","High","","","Bùi Trí Nguyên",""],
    
    ["UC_PQ_003","TC_PQ_020","Lưu thành công khi thu hồi TOÀN BỘ quyền của vai trò","5","Functional","3.3 Cập nhật quyền","Vai trò Quản lý đang được gán nhiều quyền.","Bước 1. Mở phần mềm Đại Nam POS.\nBước 2. Đăng nhập tài khoản Quản trị viên (admin).\nBước 3. Vào Hệ thống, chọn Phân quyền.\nBước 4. Nhấn chọn vai trò Quản lý.\nBước 5. Bỏ tích chọn tại tất cả các nhóm quyền trên cây, để cây phân quyền trắng hoàn toàn.\nBước 6. Nhấn nút Lưu thay đổi.","Bước 1. Phần mềm khởi động, hiển thị màn hình đăng nhập.\nBước 2. Đăng nhập thành công, vào màn hình chính.\nBước 3. Màn hình phân quyền mở ra.\nBước 4. Cây hiển thị các quyền đang có.\nBước 5. Cây phân quyền mất toàn bộ tích chọn.\nBước 6. Hệ thống lưu thành công và hiển thị thông báo: 'Cập nhật phân quyền thành công'. Lần tải lại tiếp theo vai trò Quản lý không còn quyền nào.","High","","","Bùi Trí Nguyên",""],
    
    ["UC_PQ_003","TC_PQ_021","Lưu thành công khi gán TOÀN BỘ quyền hệ thống cho vai trò","5","Functional","3.3 Cập nhật quyền","Vai trò Nhân viên đang có quyền hạn chế.","Bước 1. Mở phần mềm Đại Nam POS.\nBước 2. Đăng nhập tài khoản Quản trị viên (admin).\nBước 3. Vào Hệ thống, chọn Phân quyền.\nBước 4. Nhấn chọn vai trò Nhân viên.\nBước 5. Tích chọn toàn bộ các nhóm quyền trên cây.\nBước 6. Nhấn nút Lưu thay đổi.","Bước 1. Phần mềm khởi động, hiển thị màn hình đăng nhập.\nBước 2. Đăng nhập thành công, vào màn hình chính.\nBước 3. Màn hình phân quyền mở ra.\nBước 4. Cây hiển thị quyền hiện tại.\nBước 5. Toàn bộ cây phân quyền đều được tích xanh.\nBước 6. Hệ thống lưu thành công và hiển thị thông báo: 'Cập nhật phân quyền thành công'.","High","","","Bùi Trí Nguyên",""],
    
    ["UC_PQ_001","TC_PQ_022","Nhóm quyền 'Khác' tự động hiển thị đúng dữ liệu","5","UI/UX","3.1 Màn hình thiết lập phân quyền","Trong CSDL có ít nhất 1 quyền không được gán nhóm nào.","Bước 1. Mở phần mềm Đại Nam POS.\nBước 2. Đăng nhập tài khoản Quản trị viên (admin).\nBước 3. Vào Hệ thống, chọn Phân quyền.\nBước 4. Cuộn cây phân quyền xuống cuối để tìm nhóm Khác.","Bước 1. Phần mềm khởi động, hiển thị màn hình đăng nhập.\nBước 2. Đăng nhập thành công, vào màn hình chính.\nBước 3. Màn hình phân quyền mở ra.\nBước 4. Nhóm 'Khác' hiển thị trên cây, chứa các quyền con chưa được phân nhóm cụ thể.","Medium","","","Bùi Trí Nguyên",""],
    
    ["UC_PQ_003","TC_PQ_023","Cảnh báo mất dữ liệu khi chuyển vai trò (Chọn Có)","5","Functional","3.3 Cập nhật quyền","Vai trò Quản lý và Thu ngân đều có dữ liệu.","Bước 1. Mở phần mềm Đại Nam POS.\nBước 2. Đăng nhập tài khoản Quản trị viên (admin).\nBước 3. Vào Hệ thống, chọn Phân quyền.\nBước 4. Nhấn chọn vai trò Quản lý.\nBước 5. Tích thêm 1 quyền bất kỳ (thay đổi dữ liệu).\nBước 6. Chưa nhấn Lưu, nhấn ngay sang vai trò Thu ngân ở danh sách bên trái.\nBước 7. Trên hộp thoại cảnh báo 'Dữ liệu chưa được lưu! Bạn có muốn lưu trước khi chuyển?', nhấn Có.","Bước 1. Phần mềm khởi động.\nBước 2. Đăng nhập thành công.\nBước 3. Màn hình phân quyền mở ra.\nBước 4. Cây hiển thị quyền Quản lý.\nBước 5. Cây thay đổi trạng thái tích.\nBước 6. Hệ thống chặn lại và hiện hộp thoại cảnh báo.\nBước 7. Hệ thống tự động lưu quyền mới cho vai trò Quản lý, hiển thị thông báo thành công, sau đó nạp danh sách quyền của Thu ngân.","High","","","Bùi Trí Nguyên",""],
    
    ["UC_PQ_003","TC_PQ_024","Cảnh báo mất dữ liệu khi chuyển vai trò (Chọn Không)","5","Functional","3.3 Cập nhật quyền","Hệ thống đang chạy bình thường.","Bước 1. Mở phần mềm Đại Nam POS.\nBước 2. Đăng nhập tài khoản Quản trị viên (admin).\nBước 3. Vào Hệ thống, chọn Phân quyền.\nBước 4. Nhấn chọn vai trò Quản lý.\nBước 5. Tích thêm quyền bất kỳ.\nBước 6. Nhấn sang vai trò Thu ngân.\nBước 7. Trên hộp thoại cảnh báo, nhấn Không.","Bước 1. Phần mềm khởi động.\nBước 2. Đăng nhập thành công.\nBước 3. Màn hình phân quyền mở ra.\nBước 4. Cây hiển thị quyền Quản lý.\nBước 5. Cây thay đổi trạng thái tích.\nBước 6. Hiển thị hộp thoại cảnh báo.\nBước 7. Hệ thống bỏ qua các thay đổi vừa thao tác ở Quản lý, và nạp danh sách quyền của Thu ngân. Lần sau xem lại Quản lý, quyền sẽ không thay đổi.","High","","","Bùi Trí Nguyên",""],
    
    ["UC_PQ_003","TC_PQ_025","Cảnh báo mất dữ liệu khi chuyển vai trò (Chọn Hủy)","5","Functional","3.3 Cập nhật quyền","Hệ thống đang chạy bình thường.","Bước 1. Mở phần mềm Đại Nam POS.\nBước 2. Đăng nhập tài khoản Quản trị viên (admin).\nBước 3. Vào Hệ thống, chọn Phân quyền.\nBước 4. Nhấn chọn vai trò Quản lý.\nBước 5. Tích thêm quyền bất kỳ.\nBước 6. Nhấn sang vai trò Thu ngân.\nBước 7. Trên hộp thoại cảnh báo, nhấn Hủy (Cancel).","Bước 1. Phần mềm khởi động.\nBước 2. Đăng nhập thành công.\nBước 3. Màn hình phân quyền mở ra.\nBước 4. Cây hiển thị quyền Quản lý.\nBước 5. Cây thay đổi trạng thái tích.\nBước 6. Hiển thị hộp thoại cảnh báo.\nBước 7. Hộp thoại đóng lại, lưới bên trái vẫn chọn vai trò Quản lý, các thao tác tích chọn trên cây được giữ nguyên.","Medium","","","Bùi Trí Nguyên",""],
    
    ["UC_PQ_003","TC_PQ_026","Cảnh báo mất dữ liệu khi đóng form (Chọn Có)","5","Functional","3.3 Cập nhật quyền","Hệ thống đang chạy bình thường.","Bước 1. Mở phần mềm Đại Nam POS.\nBước 2. Đăng nhập tài khoản Quản trị viên (admin).\nBước 3. Vào Hệ thống, chọn Phân quyền.\nBước 4. Nhấn chọn vai trò Quản lý.\nBước 5. Tích thêm 1 quyền bất kỳ.\nBước 6. Nhấn nút [X] ở góc phải trên để đóng form Phân quyền.\nBước 7. Trên hộp thoại cảnh báo 'Dữ liệu chưa được lưu...', nhấn Có.","Bước 1. Phần mềm khởi động.\nBước 2. Đăng nhập thành công.\nBước 3. Màn hình phân quyền mở ra.\nBước 4. Cây hiển thị quyền Quản lý.\nBước 5. Cây thay đổi trạng thái tích.\nBước 6. Hiển thị hộp thoại cảnh báo.\nBước 7. Hệ thống lưu thành công và sau đó đóng màn hình Phân quyền.","High","","","Bùi Trí Nguyên",""],
    
    ["UC_PQ_003","TC_PQ_027","Cảnh báo mất dữ liệu khi đóng form (Chọn Không)","5","Functional","3.3 Cập nhật quyền","Hệ thống đang chạy bình thường.","Bước 1. Mở phần mềm Đại Nam POS.\nBước 2. Đăng nhập tài khoản Quản trị viên (admin).\nBước 3. Vào Hệ thống, chọn Phân quyền.\nBước 4. Nhấn chọn vai trò Quản lý.\nBước 5. Tích thêm 1 quyền bất kỳ.\nBước 6. Nhấn nút [X] ở góc phải trên để đóng form.\nBước 7. Trên hộp thoại cảnh báo, nhấn Không.","Bước 1. Phần mềm khởi động.\nBước 2. Đăng nhập thành công.\nBước 3. Màn hình phân quyền mở ra.\nBước 4. Cây hiển thị quyền Quản lý.\nBước 5. Cây thay đổi trạng thái tích.\nBước 6. Hiển thị hộp thoại cảnh báo.\nBước 7. Hệ thống không lưu thay đổi và đóng màn hình Phân quyền ngay lập tức.","High","","","Bùi Trí Nguyên",""],
    
    ["UC_PQ_003","TC_PQ_028","Cảnh báo mất dữ liệu khi đóng form (Chọn Hủy)","5","Functional","3.3 Cập nhật quyền","Hệ thống đang chạy bình thường.","Bước 1. Mở phần mềm Đại Nam POS.\nBước 2. Đăng nhập tài khoản Quản trị viên (admin).\nBước 3. Vào Hệ thống, chọn Phân quyền.\nBước 4. Nhấn chọn vai trò Quản lý.\nBước 5. Tích thêm 1 quyền bất kỳ.\nBước 6. Nhấn nút [X] ở góc phải trên để đóng form.\nBước 7. Trên hộp thoại cảnh báo, nhấn Hủy.","Bước 1. Phần mềm khởi động.\nBước 2. Đăng nhập thành công.\nBước 3. Màn hình phân quyền mở ra.\nBước 4. Cây hiển thị quyền Quản lý.\nBước 5. Cây thay đổi trạng thái tích.\nBước 6. Hiển thị hộp thoại cảnh báo.\nBước 7. Hộp thoại đóng lại, màn hình Phân quyền vẫn mở và giữ nguyên trạng thái chưa lưu.","Medium","","","Bùi Trí Nguyên",""],
    
    ["UC_PQ_001","TC_PQ_029","Giao diện không bị vỡ khi phóng to / thu nhỏ","5","UI/UX","3.1 Màn hình thiết lập phân quyền","Hệ thống đang chạy bình thường.","Bước 1. Mở phần mềm Đại Nam POS.\nBước 2. Đăng nhập tài khoản Quản trị viên (admin).\nBước 3. Vào Hệ thống, chọn Phân quyền.\nBước 4. Nhấn nút phóng to (Maximize) form. Sau đó nhấn thu nhỏ (Restore Down).","Bước 1. Phần mềm khởi động.\nBước 2. Đăng nhập thành công.\nBước 3. Màn hình phân quyền mở ra.\nBước 4. Cả danh sách vai trò và cây phân quyền tự động co giãn tỷ lệ tương ứng, không bị vỡ layout, các nút vẫn nằm đúng vị trí.","Medium","","","Bùi Trí Nguyên",""],
    
    ["UC_PQ_003","TC_PQ_030","Sử dụng phím Space để tích quyền trên cây","5","Functional","3.3 Cập nhật quyền","Hệ thống đang chạy bình thường.","Bước 1. Mở phần mềm Đại Nam POS.\nBước 2. Đăng nhập tài khoản Quản trị viên (admin).\nBước 3. Vào Hệ thống, chọn Phân quyền.\nBước 4. Chọn vai trò Quản lý.\nBước 5. Nhấn chuột để focus vào 1 quyền con bất kỳ trên cây, sau đó nhấn phím Space trên bàn phím.","Bước 1. Phần mềm khởi động.\nBước 2. Đăng nhập thành công.\nBước 3. Màn hình phân quyền mở ra.\nBước 4. Nạp quyền của Quản lý.\nBước 5. Quyền con đang focus sẽ đảo trạng thái (từ tích sang không tích, hoặc ngược lại) giống hệt như khi click chuột. Nút cha tự cập nhật theo.","Medium","","","Bùi Trí Nguyên",""],
    
    ["UC_PQ_001","TC_PQ_031","Hiển thị tên quyền cực dài không bị lỗi giao diện","5","UI/UX","3.1 Màn hình thiết lập phân quyền","Trong hệ thống có một quyền tên dài khoảng 100 ký tự.","Bước 1. Mở phần mềm Đại Nam POS.\nBước 2. Đăng nhập tài khoản Quản trị viên (admin).\nBước 3. Vào Hệ thống, chọn Phân quyền.\nBước 4. Quan sát dòng quyền có tên dài trên cây.","Bước 1. Phần mềm khởi động.\nBước 2. Đăng nhập thành công.\nBước 3. Màn hình phân quyền mở ra.\nBước 4. Tên quyền dài được hiển thị đầy đủ (có thể xuống dòng hoặc hiện dấu ba chấm và tooltip), không chèn đè sang các ô khác.","Low","","","Bùi Trí Nguyên",""],
    
    ["UC_PQ_001","TC_PQ_032","Không hiển thị nhóm quyền rỗng","5","UI/UX","3.1 Màn hình thiết lập phân quyền","Trong CSDL có một nhóm quyền nhưng chưa có quyền con nào thuộc nhóm đó.","Bước 1. Mở phần mềm Đại Nam POS.\nBước 2. Đăng nhập tài khoản Quản trị viên (admin).\nBước 3. Vào Hệ thống, chọn Phân quyền.\nBước 4. Tìm kiếm nhóm quyền rỗng trên cây phân quyền.","Bước 1. Phần mềm khởi động.\nBước 2. Đăng nhập thành công.\nBước 3. Màn hình phân quyền mở ra.\nBước 4. Hệ thống tự động lọc bỏ các nhóm quyền rỗng, không hiển thị trên cây để tránh rối mắt.","Medium","","","Bùi Trí Nguyên",""],
    
    ["UC_PQ_002","TC_PQ_033","Lỗi mất kết nối mạng khi tải quyền vai trò","5","Negative","3.2 Xem quyền theo vai trò","Hệ thống đang chạy bình thường.","Bước 1. Mở phần mềm Đại Nam POS.\nBước 2. Đăng nhập tài khoản Quản trị viên (admin).\nBước 3. Vào Hệ thống, chọn Phân quyền.\nBước 4. Ngắt kết nối mạng (Tắt WiFi/Rút dây LAN).\nBước 5. Nhấn chọn vai trò Quản lý.","Bước 1. Phần mềm khởi động.\nBước 2. Đăng nhập thành công.\nBước 3. Màn hình phân quyền mở ra.\nBước 4. Mạng bị ngắt.\nBước 5. Hệ thống báo lỗi kết nối và cây phân quyền giữ nguyên trạng thái cũ (hoặc trắng), không bị văng phần mềm.","High","","","Bùi Trí Nguyên",""],
    
    ["UC_PQ_001","TC_PQ_034","Hiển thị thanh cuộn khi danh sách vai trò dài","5","UI/UX","3.1 Màn hình thiết lập phân quyền","Hệ thống có nhiều hơn 20 vai trò.","Bước 1. Mở phần mềm Đại Nam POS.\nBước 2. Đăng nhập tài khoản Quản trị viên (admin).\nBước 3. Vào Hệ thống, chọn Phân quyền.\nBước 4. Cuộn danh sách vai trò bên trái.","Bước 1. Phần mềm khởi động.\nBước 2. Đăng nhập thành công.\nBước 3. Màn hình phân quyền mở ra.\nBước 4. Thanh cuộn dọc (Scrollbar) xuất hiện, người dùng cuộn mượt mà để xem các vai trò phía dưới.","Low","","","Bùi Trí Nguyên",""],
    
    ["UC_PQ_001","TC_PQ_035","Hiển thị thanh cuộn trên cây phân quyền","5","UI/UX","3.1 Màn hình thiết lập phân quyền","Hệ thống có hàng trăm quyền con mở rộng.","Bước 1. Mở phần mềm Đại Nam POS.\nBước 2. Đăng nhập tài khoản Quản trị viên (admin).\nBước 3. Vào Hệ thống, chọn Phân quyền.\nBước 4. Cuộn cây phân quyền bên phải xuống.","Bước 1. Phần mềm khởi động.\nBước 2. Đăng nhập thành công.\nBước 3. Màn hình phân quyền mở ra.\nBước 4. Thanh cuộn dọc xuất hiện trên cây, cuộn mượt mà không làm mất focus.","Low","","","Bùi Trí Nguyên",""]
]

with open('docs/TestCase/TC_PhanQuyen.csv', 'a', encoding='utf-8', newline='') as f:
    writer = csv.writer(f, quoting=csv.QUOTE_ALL)
    for row in tcs:
        writer.writerow(row)
